collections:
  - name: ansible.utils
  - name: community.general
  - name: ansible.posix
  - name: kubernetes.core
  - name: https://github.com/panoptikoe/k3s-ansible.git
    type: git
    version: master

roles:
  - name: geerlingguy.pip
