---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-kuma-monitoring-creds
  namespace: uptime-kuma
spec:
  encryptedData:
    password: AgCsbVeByEkqN3d+PWnTAblbQy8TrkH9/oZlrDDlZQiQ6T68JFgGeK4a3qEOf8ndbrPLsO+sI30UCmvIGn6uvCRZnJM/cyOaogyrar6KO8Sm8vJeyfkG+0WZve/dIF+kXcqK68h67A2oS4rg24Uzbb+paGn0tj7pIlbwsKgUS1r+wvCzOIhmqzJvUl9tDvOgwZfrNLYD9DI/gH+um9j0oOdRSt/EuTCUPoORoIQ25fHO9azXdI6ylEinlU0HMzU85rrlnjf7BofaP669z7jp5EmIkLtDZSzZH1sq63zJq9MV5+YHUGRTBAy6m9Uo43ztELE5SaUae9i68QjltO+eGzxtwPTcRJ4FpiM6zUuPnlJDm0PHtc4rBqtDd786FYx2a1PJ1vhDVJcSE091OTfpIzXYrfWy/byhkjRnQ9CKkiixGQOqHtt+yUlvfdbj92sZdJNxpJrK6I0gKACTlPDEuPA3q/6vIQS+PnogYlrW/NaRHtiRG4uI2JbggvgOl5yVmS01fvsLrT4zyarRHBTcrEse8lvyWDzTYQWvyIz0qELnBqpOgxcC2zOp10mI3XMNQ2Dn6xte9kv0MXdN5fAu24wBH102gj0kdPt+AaG1WHPUfAV9O6cdtqnvua0N6uAosNkGMdHLr7k8tdNdIH91V6+REOyGmN1RLvbYJgYuAceN+BHPRm3HbhJcOUjTQQ/J8qrEi8zGbWHeNXxL5hOyPIgZT4l0r3v5Tm8mjdHRAdtMpxC/BOmFeqAbmEnWEg==
    username: AgAzl1UpD63FKhA7l4N3/2IJgovCBMQhgrjE6EWH8RNcdUD2gS5Su6Qc30U5OcSJDvplTYoMHUvUXOgV7p/R+Ra6wfjQOkgB4KYDtqmPuVIxAqJkepHtRPk5khXzivC/15zqdBy2VGg9Akx2oEUWi8IJPPm9QbRPJnKYJ0o+4RiRAOIcFb/T8pCKMnUINh4lslRxKwSC4UOE6BJrpWmVXqevJhSNQ6wWWLQv9qgZhsmYaKKp3bpYk7IEp7jFb+In2JES69r0f4vPtx+8N2O9As1TyGY5DcA6/07cVCmkxUO5yvlIkBfo4jLuVXFw5dlz0X3Zuky6nW07boUiJYympcNSRmCK1jGlgSpkm12xh4Hj+Lo/RgkbFxB2HS2u0TK2GS3cQBTOQ6WauN8m4nrL8lGaycVkkDP6hKObD7Y2uvcTprKVttNF64v8oR6NMc6YQ+4Ate6pvWTQ72touNBTgjqN2GQ9Sas47y4SAnUFW9mYffnWJToS9Keu7MKzxtIIo5cwzaOz7sroyhSqQK1pqxjUEbv8cNeOi/WB6rhzcyfzrMg67zmHAMaGKhD7rQz6Ra6lDRGEl3cLkMk52LKqwd2giEVu3o13LbXAKNtFB0v832zJgweFg836npI6wYG9C0qLY0t2LCHRnHMowvXu+KoHefSnhP4rXjxUPgbuenZSSRRoBFkPDa2xOMHuhU7dy0J1SOM=
  template:
    metadata:
      name: uptime-kuma-monitoring-creds
      namespace: uptime-kuma
