podEnv: [] # name + value format

image:
  tag: "2.5.5"

useDeploy: true

service:
  type: ClusterIP
  port: 3001

volume:
  enabled: true
  accessMode: ReadWriteOnce
  storageClassName: longhorn
  size: 4Gi

strategy:
  type: Recreate

dnsPolicy: ClusterFirst
dnsConfig:
  nameservers:
    - 100.127.99.35
  options:
    - name: ndots
      value: "3"

serviceMonitor:
  enabled: true
  interval: 60s
  scrapeTimeout: 10s
  selector:
    release: prometheus-stack
