---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notes-rag
  namespace: notes-rag
spec:
  ingressClassName: traefik-tailscale
  entryPoints:
    - websecure
  routes:
    - match: Host(`notes-rag.internal.dmhosted.com`)
      kind: Rule
      services:
        - name: notes-rag
          port: http
  tls:
    secretName: notes-rag-cert
