---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-rag-persistent
  namespace: notes-rag
spec:
  storageClassName: longhorn-singlecopy
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
