---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAbWKvXQp8bMRyEi55+5yOeX+V2XeuqSuBwwuMgLiNRGQ46gI4x8VUxe9foQootAF75Jr7QFwsMdVXrlp4W1Qi7T0CYDAWkSiQtoGuaNp8+8DoEgd6ONAwt31eD9dWzk7NGyaPo3i179l0Hw62+qL+oJtycM8DEqB8+WtYIQOtVvPH4J07gOTIobirq4+YKdJYsk6pJBOZVYzanjJ01XTvDIPxEuHvHLGlZnfR7yEafp87xu6ubrZGgEY2JjeEGz2RDGAdKJNgovURuKJqWwOc3oZjgn0DwyL+b/UGamuc6q5a8f8G2pi7VjNHWjpV2IftS09thuSVMUfumR1IaonCIKT6e/DmTaGWM+klvh+VOAcHqeMjvZmUgqmxwTSePMNhKNWUXYgOL8K4xfBmS6X+YrdXgBIDPJNdxWAJuwnkoH/L/fScEbPnSjFokFk1g/3Vx44d5yD8BVCvGSLlAucFqerEEy3xqjnz1s0fyjBKLTbzx64RLGrr8QObF9bmCilGGuMQR8ER4T5VseYHOI/kDk0Wln9lx/R2oY/He3xwSITAt7Doon9chKYFlQc8pInaQ8WBqOStU8mr3/E13/4W21yWQMthx8gRaj7Tnwn9nzhjDZFYBHJsymRt8VB/qORdn34l3HLBg48xgAATBi209CJmZrNOmk0+h7Qu7goJUOzoh6QxyKqhWbvbJ4Euz7/pTzaDXYPcDqEoZ/E984peU6cxdhtUkwT9MBxdvkmDRiaF/x5kGx8J1b++aS/VYishNtrcLpgNCwGcRe70Z3t1oSNrGXzxR4ZBawX8ND1IddJ1Sfys5Yb0IsjljMCaMnLSxXJDO7RBUtWm3MzTgKU2J1oWnljY5ycnt0bFcmGVEm4YHWY7A73ca3ctekpdMptj0M4K+Iz/FFoTgf/P4Ygfiof5ewFcqZYeBvpE/8L0P/Slh42k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: tunnel-token
      namespace: cloudflare
