---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgBWhCNWvNIvz0wp27YgSeeiRgPtfrwBWRGt+twGhZHjTkdVP3AIpqCPT/EdvC+pbz0ljfZH70YkWokuTvVy3qF2E1GkF7FEpc2qEaTMzzDPxILLzm7gdUDWyXEInwZ5REIuUJkkZHIwar8kLcl3X3s6C5e9BFbDWisilayfD4EjYzQA+JhRAwL7YbOuuam7d42cy3HCbufYc5DiXYvnzwDukI4+m8WL/yX1xIW3f/nSe6JHI2yHbHKzlBvoTRvo4zbkzcL1vFc1t4lzBzM0H+UGpjF0jZfCxlKtT7u+1/3wyvPoAQIviKkscWDaKAjVZpxWPYPj6IGOeiGaCgAizwwZHHm9h807TojD50YDhXTI2ZX/odN8bhpeOCGotGG3zNoKyPEW/my/Rypoa9FsgOoRFgH05iULGRGu8jrr2gCf0I3LH1adSAzY/RxYdUcfOiBu4gadRX5VV6tQPlQlYAbk/XscvfDO8CgdrEl6+ylHHQhePWBzYdtNIdrSk1rTic3IUBWQ7q5ezOFU9DUc8Uj+T/twNOMHPbi+b9lBW5C2m/8/p8e5lxhR8p3O+zGDX/uunrCZtjXUqNwicRskw1bgpTuyZ0ODI8rTGGsFy9aIQ4VeRyISPQbGq9aXIJHUUXtV+IwK/VbVvPhWj8YSR7GlXK2bNo6odHyetdtwb6gH1/2513JtfzwAlYXI4WVwGWtZxjwi+gJ30S44pXoFdynx5wGKKpVVb2BcvB/JpJyv+cMWJ6ax/gigyAF7ne/NRBsmrBGws4Igl0NJgUnEX2QDIKxOlQU6nfOYyEPBNqXQX2chiVAxS+PQKubD5XTu/anFpCCSUHQyUz7RJRkZ7yoqqHKGdse/7Zmkn57mBYUJsYSmwBqmbQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
