---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-app-db-secret
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgAdUeJLxP/52H3ihE7H6oOGwTVeY7Mu++s5x3l+/7EMd2PI8MOPLssnll0NoBjZZfn+Vo0qQMKCXT7aNzwdqxDPQzvuVs4hIY4iJJrZhiPaD639Mqd2CLxi3/EQFgMZ50/ncEWEUEaE4x334LZ13qwuzzHxIAPgJvRoRrqIa2erG+lSO5KcUTT5zqlsbSyrvL2e7pPw5j5YZ9/Y1uF6p2I2RiqpM2eYcWHEEElzsph9aG/sLdO84S3AskVWDpVXQ5j+zWjOSonY6s/vXx5WvXec7IKtZDb2YcCJPCeaKIPeQ6p3uP9t/dXF1RX/VROS3j43oI1MhIetmWUl+vjVuIUYM1kgV7IUM3KUC+tjLGOJ3BZ5cDhQ1R3av7zhjfwgNbrUBafUU857zERJpL5r23Ex9tMpgvztFS/VZG6oqCdEJKhtl8gikQD7Bh1CgfzzI6VfkrmfJZjE8Z9EWLL97hP3BHdIZjBJSsdrd5+AJn1NhjaBwrpPbRXpUriyRIem7m64IiouHfo3evB8udbev57dvM0kMmU1jEcMdcgIUFSOcCHk7m/vMKw+S2pEjwb310JPiJ+bCBkU0ytAsMPVh/sPoGPFvjw2pDd6E85m2QpcDSxQT9mGs2eRO9TJFNOY5L9TXlXurGPLf7xhcimOquixGpXx5ayaGEosrKXHSXu74Cq0lcHAp9iL6TPYyVgomKjwqXZmI+IAoXRclHKVidLi
    username: AgAT+42hUTVRGtpZXXDR3Cg7Y0J5V88D72ggvqacoidVlxuvFpfOc6ReVeZ2YCjirmOfyUvf8PD7R1h/qDHKOfP8oh8297JfNbrIZ6AzjFpDBcU4c1RZcu3uUpgY1DGikGT+Niy8/r72U/MUAQu1S5QXGrDpK40wngzMq/j6aiIN567rUs+yEiHpSUwH52i/aLq+VL3HYPAs1OxPJMOz9588L0w97Ws0ihzuY1qmoCafr3uBZKQU1W+WHPdyFbmuj7Qm94acn60Ue/8NJ5YySzFgK+AGZCQaQNsa5gChlwRLOyvxCBKT90JEKdXxWfSVG6hXQ07CiVkxdeFvBSSto3VYXjnHqAXIrhUWqZ8mT7r2nT94lgX+bvLdWZy+WbXE9bVLzbDPeG30mPTN9Q9MpAUjfaA05nCGSFg4LVXobILEl1LzqEL7jT+KTwHojiC6wxuynXuG3kHR5TVsB9eX64HpBCEZ5KfCQ2fmfBIgtg4W2gmC5mPwyk0yWtB8bzy2DY2phWcNYOgbrK3xWy7AnjKXGty0g2QW3tpikJORADHr7RubELAmIqmdRO0A/dn7lSDYt9cbfMHLheH8tYoq8SDKXU6b3lhCSKg1rljlVSo2o9bzcpzf4UKRcX3RcXWQqefDW2uIvs9kbOX3p6eboTtiUjmO0ISpnja9oWnFmnB309EO3Cac/6t2gBMWhPiNdGpfQ8kGq1pylBzfYg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: vaultwarden-app-db-secret
      namespace: vaultwarden
    type: Opaque
