---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-cnpg-rustfs-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ACCESS_KEY_ID: AgC4vJIfP18i7Gdwf14e4gtryqUDbK0/9UeRBm42zfx+9s5BzlacLmM1NIXRQDmzHWudXNpx3amjHYGgDKTU4HjOxKArXLg6ykpeonPeVqxtfdV0d34Z2wYnIicr31CgDD6fS4ZiPK2MT34w/WzL8GOXrRQWIjorKvYaKBOaaVF+41DAshnejQbGJYhR0dmClW3Mna44DMRJixaaqliQ/HZtGD2k6FLEhZzW+Mkq08g4r0aanBiDMZoi/PgHgezSzfl/OSUXQ+Gpm/KeYQprsZy4HTMxdsKc15WJ0PBVvlx4p5fttND0vjZF3XvapA0ArbHWnhuPi1x2rUJGpxmqbt4gkfTj4fksOQSC/TIub3vY/w/A4IJ0wxpi2gfN5+AYE2d9NTfz2kRe0EL1wjRg8T+bqyBIhcJkAX70AyOY/zw7oFJ0BFyEeFMCBORW48jYvFnqHFXE2diVnfPslpJk7OuDFvNp0XhLkpEoXJnXT1yyCcByVx0cIPXdgTyi7K7RVT6WxURjBfNqfq8ryFCoUw6HBallMbREeLMWtCBZduvnlc2NiEeGI/PPttS1MR+t6/nB73oPbtU6ZhgEYzgD9y59mZILbV2Zz9PpmUkbaQxQIc2NlLz9BN4yAueCwp5FJDgm06mbg/goFB5O9687kfw3TReQYV9IfgYo2gVD6yPyeaLG9eTD2kNOygjfAZ5jxsD7f9KSTM0k+suFUbA=
    ACCESS_SECRET_KEY: AgCBLMLdJKR4ZyQNSJelRFDcxkmsRzsq4Hr+EtlJPzs/jS0uDwtIWsfuPUBmuGL8JCIhXl4NWLZvZLFtUD9L+W04muh3Hy2ZT6+OVx6Q0EWzy4LFW1jliOVHVyZ4p+X/IoVyrWzCmFsOXXzDKSo7t5Ue5c3xUeBjp8NgKLKQ8xq1P0j+FKYwtaL67Pacy8BFdwpw7XhcLA2SMt2CU0aRMC77gz5fEQnkcigg2gcC+Xh/dOE1Ala5HWupyvq8YL4HkY2EEsOAUL1GoaDYCq5ZZOvzltM4wdxw4htiINNYKJ7n3RWElr/zmcNgipUSfLKXUy3riROrmqnZLQEWJcDPTaj7HWOQWvRrWbzuST5ua138k0D5rWELU4/LxN0DrzsZCkBDTMRPUe6CBgmQg62vTJd7q1MgGTAY742s0/VsCuQCZybWO9Igmc9nZ3invZmbAnayZiu1vknvK7kAJGFODMOVIwDApDRnK1fcS3oAXT9PNC0r5esuyIZfKKLMZUgucWhw0WrnuMg15FQWWNZa2A/w6QMqdKj0ETJaNSfHnXPbjzV2IshIQZEUZ1IDPVU+s9BdH1k88VhpgyZTFJZPIxokYvWkwOpA4cZWjocFoZwaxho8YlVLR7X173WhpSZ1DUU9wwCIoGkAtX6fQUQj7zRxAUQSoqdtAWwRhzPj7n1VLne49v1inY3ia3xfgZVlDpmu6AZU6GMMrv13BHo7UsH8DxNNSe1hqw/XaFDY6bYbxrq96sBbLJqZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: vaultwarden-cnpg-rustfs-secret
      namespace: vaultwarden
    type: Opaque
