---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgAoLKBJQ0NHguHtCkB+wTzDPJAQkBK2TrEMe9m0OnTAkOWb7B6v0v5WVaSJ4cykKoI0ChaCWwGVGBWMe6X10FJVEVC28DM3GkJVGr3xXORa/JZgH+SPEz9h9KAF8Kg/8Ygdf0nRHyIwTtoZmQrg5mfX+owICYXZEcS1HS/6+aUwwh81Us/KwJcAvACQwQbqAXc9i+U2QBOhRdUztmFVUdXmy5JQLJGqKR+0S3UHNyhTVWoAugdf46RjOPKbaH2hDklfwbrRl1Bm5C7VoaxMxyEd9mkW7ZJ1OrozDatWXpfZIaD4AeXkkUDPe18d8pKvfdN0CxsuCZVeZEtHnJvDlRxSZL9FZF5sE6FBG69s1JAelQ7Kb37DWZdx4OlHjYj2+QUeYcZSJiYSs4xDs+yOVDFYFoAvolk5IpTRuVFVCTg+VtcsjOJCjxRj9g83fabFdV3SA/ta6JAgBsI36oElsqdzoMuP7w9N2y1k4j+0ieQFnkHXnGY7TMmP3GmdJ1+E7bRGP25Fd7ex7DYqGhtFjTAl8cCWx7fc2bc2qaeJTSebyE/bc12+b94Q4RWR5iSu+9J1apOvP1vrZIZoUC7jEQMde7jHLIAX+xoxqvbqVch9/9g6iWGKJuUlYZrqR7waMffF6l1rIPQ4n9VRRin9aOYM91sJf5Q8TbXTsxy5Zjbds1r8sZaN+3zt4Vkogo49VNNXV526tW/hr7/wd4LCzTIg92PUBKd5MdhKTzYUEecMFSNP0oKaRgnyw1FDc9eVcr2gxB7BmqktWKzuzHotKK8Hsl2EbYxMMLdFkSCYnXmSkQ5Mp6DU+h447rY=
    username: AgAH5ZpI4DgUdkIR3gppI2Q3W4jsYtT8RXoUh7zYmUwUlVlVi8Cps9aCF4fMjEyra5kGP0ohArqcFomiwDl6F6+BT0RBJ/tFLj2CALfYB6faDkWqfZCVlnUPVge4qv26YrGKv3VvPzC7H1AL9uO7pKJ/VaWJKds+P0fBOn9pcOuksIe9mN/qZs9bOY4tiZ4VkGCY42d15cdfySatyG6b1yEaDuuMOG10Pck4eFJ7+cnImR3HhC0uuJRBdaE4ksy+oHfl+qQUNJYcAT+B+TL3h8KbfWqE23MjdJBD83oDJeGrIloZT6oPZeo01GZmpF28QO7RqSBDqoIWQm63W2RGXup1z13yzkO2lfs5HU7W5xBVm2PV/CYuu3KID935Ncvqd/LW+fQiFDCRudg0U6jt5cQriEXMc+H0UnVZcJI+2lh5FK2EJxwU6B03XqGRlPGx1E5Mg3yIsR8CyKMEPaCiLhGXxO9/HInWIg/LT2R1zx5UzoE4zC0sPgdaZaYqRkoXVy1tF8jEbBCB4zgsqM1+wo03vD46hXq/NyAwgACgu5J+pVWxVIz/L2+YaKpzKPg4jmgV6MQdOZ18+STkQ57KZVJopTAoqwsPdkXMKXPUHlBDUn/6TF/PxDOauODyvWMYQd/iHWdtLXlc1cQmUUvbRu+aYy5RfbLUvGCJ8U19G/FzQYoVOdEn0P8s0zrnZksacvMh0PM2c/DCSgVDxLCtHCE2/3w3/HI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: vaultwarden-smtp
      namespace: vaultwarden
    type: Opaque
