---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: cloudflare
spec:
  encryptedData:
    apiKey: AgBm6WSmOgrgAQoMGUAvFzLpePozRjG3VetK4ldvvHdC4wT0NpM/v8Fmmaj+7YiIMlAHIUmC460I8bGQ+V2PYQj8xw9TZfgVu3K3Gvu+etu/YlFK1r08wuxGaLae+6H5olo94oWPesbNG+QMWciSs/CMdmx0fzdoF0EED79T6BTCu5nEejGq+EQPlx/mpI5XZGQpQ+F6kL4yT5VKAM9Ld6kv/SWGgKIL4AIvdQNmW5v7GLvWKyXnQ+g9XrbXp+Xyw7hR16/tVt6tHJCSNmG4M+0idEFgaUJNIEQqw8JjRHb5D6ZsCUyxCZBocuOEdQlmIGw24WjJji8k+0sWVqJ2kwbwMoayz+VhHX4H00BIk0HQ7fYUdpNku1yLC1eSQjM2JvUwdjWe2H2TCqlEIa0DvLRJaGfcLcZLqXppcAenKroTaugJrMIVQMWdhb9DV8Og5t3jyg+POJWDCG7M1EWNZesLV8UKtM7Dwpzl8gE1CbVvNIeKMb1Dv/sBwYw9vUGz26tHZT3PUGTUTX6D4f5nRXt4f1dMWbhI4w799VsI9aVRUL2klz/UAj0UbgiRd3QYbisL9dt4GXSiPHUpx6nesbgJHqyoQLMiPz7WuQHDrsB2UkfrW29f4cJFWHGcGJZsYpDH+cpVXLxaO/2AhnngPesHrGavvYp9I68qZC9p2ichZTUo3piDsRNzqvTPGrHrRpS/ysUJexIM/pL82pdAhMP0qiqpReuKKxS6QHRPnILtJ/NvmKKld/48hFWtiRnYk17re4GNbQ==
    email: AgAkeghoCidk3YG4JZpI9WiZ6vSMiqUlBumTTreLDI2kJQG7r6lq69AS9hkSapCnNVtwcCeLj39LjuXYFUyQwkm+S26S679xypjYQUYghBERgUw3VFWZPtJY0bU3R4g/U3cdNr3w6XyrrE0YA7lj32AbCvAIrFIHhDdgXTAg8BKNsygI2sWCqG8K/PraS1CZDNuXPaX0ZwpiCbS1SuHpZBpc3XA2zG12CBckZDisuWTtyJEDjwwuKkb/kXKKXsPVKAyn+qTtslDzWHc82hD00HNHw21zWjoCHkOQgXbGlm6keUH/AV7RJcd7JA5aAvVzofA7kCn5oKqQ44lbaWrRkHYiHl+neEQS+QkyMhWdKUeSGxdq+bG9alFPbddwfJ86N+h9iZj/KZHyUu0jUDfahw6kqXkS1hj41PBvPDuWZVQJb/vFQ2OR16ftf33yPjQUsmQb5HKVIR+WRAQOHDa8/Hi35F8lxNOJAyT0qKN8bkOm8Js7z5B+O9a9yf/xUZmLdtmuCLyObauEvOFOROAxDnmd1mS1uUGK+bUpTzmc01JksoBblMihXe5p3aiOw2vJj456JiMLL2H7nKjKdPz3Ho0+ZHldzntlotddu/vr5EmidQie13FJEXQK40rpTL+bP6wXx3wpDqWMuV/Ko+xJSYJS4XQutKGRRk6MOGAvW5RSpl61Flg8A8txkG4qPupdASIQkhF2STaM7HMHP5Fknaohweu1WSc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cloudflare-api-key
      namespace: cloudflare
