apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.4/manifests/install.yaml
  - argocd-ingressroute.yaml
  - github-repo-creds-secret-sealed.yaml

patches:
  # Edit settings by patching "main" ConfigMap
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm

  # Edit RBAC config
  - path: argocd-rbac-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm

  # Edit the Deployment (add --insecure flag and resources)
  - path: argocd-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
