[k3s_master]
heiloo              ansible_host=heiloo.taila7b4c.ts.net             ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa
gouda               ansible_host=gouda.taila7b4c.ts.net              ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa
overvecht           ansible_host=overvecht.taila7b4c.ts.net          ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa

[proxmox]
pve-dmacario        ansible_host=pve-dmacario.taila7b4c.ts.net       ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa

[k3s_worker]

[rpi]
puppydm01           ansible_host=puppydm01.taila7b4c.ts.net          ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa
davipi2             ansible_host=davipi2.taila7b4c.ts.net            ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa

[others]
hw2482              ansible_host=hw2482.tail2b437.ts.net             ansible_user='davmacario'           private_key_file=~/.ssh/id_rsa
beta2               ansible_host=beta2.taila7b4c.ts.net              ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa
dmacario-desktop    ansible_host=dmacario-desktop.taila7b4c.ts.net   ansible_user='dmacario'             private_key_file=~/.ssh/id_rsa

# Aggregated groups
[torino:children]
rpi
others

[utrecht:children]
k3s_master
proxmox

[k3s_cluster:children]
k3s_master              # Master nodes
k3s_worker              # Worker nodes
