---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker-app-key
  namespace: speedtest-tracker
spec:
  encryptedData:
    key: AgAp2LIBnx9fMS2uSBFyV//VvfaEUqjgO3jH4WkYWE7Cn5KwzaJ4pfZY1cNXWhXwd18B6Qrkg3kBE4bb0T+2XIq5ffUxQaD9DXfjNRC11HbNnsxmAhvzyU8sZhxeW1YF03KrDrLh0dDYk+H3D/1QovtJH4yPQOVf3Jz+i292D2gIV3BAPjRg4/jVT+oGoJUl4xWGdT1SozosA45E/jqb0RpNwFUH55HWj/9xxf7dG7Pujf9F4ojBMz/q+1tqFHU2pswVAPahSCUGEjLybp4T5o4EVtlkNnHHzPJ9tCgT+zbOI2t9ZsN7HaNz6tGiO7ISCGb9ECvGuwCdHdQficW1k/terQC71YdW8/mjxCdkz0/X5yYYe8l/dpAyC17R+Tbnd5dd1CDRUOTR5S4i3E9EYJJwJyyJWPsz9rVQeu3cwJU9X4eH262N0/z2TQDIZIkDmVvvy96o9t1txblXT2agxcxYyjRJvBI+yB/V8KwmuUyEmoDApC2aZKtZc4E74KNDWpnytOSsq+DaWzBO8iSMdZZchXVN1ulS95uy4T2KWZCVeTGyKrUou8yEOaEEKHCO1DnvbH4K7N+4gRs4KtJpaeswd9kiFRy+kaHdGjhh7xxAD7QY1H28VHDNz0COHtUoN/6Q9PtBDbvPJ5oJYkNILEUtFWGfTDEipGOsR2No2fiaiiCc+fO9q155Bj+RE+fnGDtJhTuk5snJhpihtWeVpWwwoLklTxyOwt0MvmBaDWYNlowHkbaV+sXMafjQ7JwkYzk+6Uo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: speedtest-tracker-app-key
      namespace: speedtest-tracker
    type: Opaque
