---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker-db-credentials
  namespace: speedtest-tracker
spec:
  encryptedData:
    password: AgBZhVcaEOa78KOHI5TbHlLydc7mUFduVBe1nkooL3M3LR0vPGswIt2iE+lgtV97iUdgnh0DUum24Y6+OVG9WdMQdKHApGqFGqFRYYxPW/GGIfES8i0LttNU57pfB+geJVySB18EfwlHMn5SY40tzyPvpZ9c+Kx+avjtc5z2oZ073Ib8fDe6fFJ3rsSnEuXf9IHYJ3dAAPdjbpaXy9g3RtiVsOvKlpP1FEU+0XV4a97Of+FTY3UeGo7PCS4eBoOqqOvbR+0WC13yOdCEOZleFtXPiUIBCa+cFeHPt+oI0FsGvs1/967Yq09JlzJdLmiJ7Iu364LyOkNF7aHg3z79Hm4CziUetQypQtgGDSCCnSxyR6J+9CPuA6PGhVOcpmhntCcDr5Q4h74GmBA4ScalzNEiSHgNjBW8H4lokosM+rVUHZt2aOOAwYWLT0nraTIio14vioK84fNiKoedr75/pHaaxApuC7s6R6mp58AoS6So9HDhH3rKHKdTsZcjU9WmAjw03iZBMt6zVnO1kAreWUeXos59b80GuymcFWByOgIEYKlB63ki8ZzEid9LpFPfqPpm9ZzPDsf4RsO5JyeXZ7Avq3HM6az8STOlAmjrL3keQJ79+Qlv6gKljBEA6PrbuCjAhN22WOog/VMw8n0u9ZrmrNz8dIkfTSTdjzt0u1iN/QsTK60bSZI+4e8i1rvdAaJ4ja4oyECSNyaHZi9ETYJV1xov4FqIpA==
    username: AgAOn4I7oLUM5eiOIhvz5oZzz9WuXVsq9A2Z3p0cr9AQwTPyWm1BcvVIk/wuFy5qqFkQ/pFrEoB6mbw/RdaaR/spJcTBoJGf9lK6ibzQgZ/4i2nRwvsF972phLQR0o7pNjvhU+/waf+VorXzuLBc1xeLKyZRGtzBh1M7CndLPKow3oUbfgw+poZSxDXdVj4naGtIBXtHDhUvQEepoS+GwlYDLzTT+QLZJXGjf7NTVSkKa112mWIkyIcIZU6HYgcg20EPkFMbDG02VCvsTZFopJsnQ6geTU6xKiqDCmLIVFlnMkjpY3BT/yDJL/Irsr+dGcqDxMx4SnQDFhPNOo54w7pCCvPf7pBmyD787XPKlkbHOaWMaX3zwObmU5/ukb3NomDCSK5plZlNI8vCspLoXDMHPW3nDs/CpEhfaZssNWb5WTNgJbIZHi2aXTNhcuu56vWzdoh4VV389vtl0RV3EhU+adgEjaTbyCl1M3hGQp1KjJbeXrufgYHyWO08iyz97IIWWcTi70cDm5kn8ghtwQzyyg3wlPZbzmvhRm8HG/M7Gj7vQ0Q2BLJ96Q/4Y/jy4CfNDD2a5xlPy0WT3eC6YVgfnVJ8lx5j+4UKA7c3xF2a1214x3x0fPIN36FPi0hBbiBgFYfC5VpTNRYzBSpHP+sJtOuCgKmf37cgW5WGXnMXAWtFEjd8boqn/UB6yJ98ug6z+uvZroo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: speedtest-tracker-db-credentials
      namespace: speedtest-tracker
    type: Opaque
