apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-tracker
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: speedtest-tracker
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 100.127.99.35
          - 192.168.178.2
        searches:
          - speedtest-tracker.svc.cluster.local
        options:
          - name: ndots
            value: "5"
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:v1.14.7-ls167
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: speedtest-tracker-app-key
                  key: key
            - name: DISPLAY_TIMEZONE
              value: Europe/Amsterdam
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: speedtest-tracker-db-rw
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: speedtest_tracker
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: speedtest-tracker-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: speedtest-tracker-db-credentials
                  key: password
            - name: SPEEDTEST_SCHEDULE
              value: 0 */4 * * * # Every 4 hours
            - name: SPEEDTEST_SERVERS
              value: "32582"
            - name: APP_URL
              value: https://speedtest.internal.dmhosted.com
            - name: ASSET_URL
              value: https://speedtest.internal.dmhosted.com
          volumeMounts:
            - mountPath: /config
              name: speedtest-tracker
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
      volumes:
        - name: speedtest-tracker
          persistentVolumeClaim:
            claimName: speedtest-tracker
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: speedtest-tracker
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  ports:
    - port: 80
  selector:
    app: speedtest-tracker
  type: ClusterIP
