---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgBO1gEBqQOZ7ZYUp3moXALL3fZX/zpMNOHo/q82RGCK6R1vb1dCDMIALG0dJ7T/BbWwQ7r24osmW9Bj8NDI9ZEna32Au5OfZc/QKqzlvxEK//CiSkTDbG31s7fuhlLuk39NOZN77goJB28X/oBo6HOT+6lRc0cxXwCcbWMCdLVRFrBR8/eH9M+/368fyyq83j+vXnZyHAPIwvBJa7M5Itd+aVewcXls0yI51jP2UPv3CkEBiuo6ZDDaghdMUE/liBVLbAQ8KKdFOynZJJbnllhTsYGClbAYn/VgWyHKOoxanq0cZmOzcx7uvCUmftIkTKJ1PwDBjzgVss8sqzoOuHsGZfqplIgiG7EC3Opqi/n21Mk0/SCrBG7UI83aZbdxuprqXtZD5anhEr7nG95Ykyu92KuQFPvXte1POT8oRU8Q9stHHFPHP3Jw+AIFxHQtcjfmb+fHaCDH63VMQFie8ES21bD45njP+TOBuzPerzsJ2uAlgsFCHiMcko6NhwWYxugTig5i0uD1wM3BXs+RhOSMw98RWSrvxhUqceDArRJyfJyXDkdL/UxqJ7gbeIbgR4+bbR3AbXfHTqyB7D2G8Wbx/J9J91uUTHNIl8NlM21vO1jZ1WMNI/czGJ7fbuFBhzrO6YYA4MGbGyfPz9I3KaIcIzAErOfdj6oz3xBAjGnAnv2EXt/UdlZv8VtWhqXT3ORkfDWVdSoRmhfjDsMHqG2MFXc=
    user: AgA28hiKcbvH7qeMfB/Y73eft1yZUH4tARYf5gdXuBDe6xitIA3tnnZ1SGcwRA4OfihBcL1CpUJgNMNwUUus1s2ERp4TolzumeL26bE4QXLGZRvWtIOxY/gwJAms2c2CRvrXeYNT33wcvekFqnCdi+aMeapQ4HmRdPw5D1lWpxsnzG7vI21YjvOKyhAvKdIdZnAtD1hwlfcDDdoKj14KcTFdaTRP4KtWqCVQWhCDeUNUFjzKC3q+Wdi27AvJ2+p4LhUUD1PssZeT70yx/neSbozKTVy7tM2K633cFm8Oulc+aTKnxzpaAekKzzwH+2vUdYQqD1hh9VQSG0dzmbFfCcNtiUJSsvnpAXaqbk9+SGd0YbvA1aWYIVymCOEMP6ZyY9vjF/o510fyyhbkMdmleXFEWdjkAs7oqEggmXkEXqI0CxHxF1YZg50HHjb7zUBoZZoAblN5c0SVEEYx9IdLQMUpffelTrJEv0BrCUVT5w8ApIDB7izFo4JizLI1q5zNUbpivIGFx0whoE0aKPRWorKssDmgEH0lTUCNEUb/+hgZX/DZitJN3CX+iEEpnd571c9/EEW9Kk4V6NZFJgvtlkmmtV7N1enfq+g0x/hOEJkohA/IcBtcm47I1bX5Rz3V/6LZV/XbOVarmWLEgOAXO2Pa71eFJTz2SpU0tUwpVhwiesYkWeunkNgaOAicAKrJ7B55VlqSaw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
