# Service targeting port 9100
apiVersion: v1
kind: Service
metadata:
  name: traefik-tailscale-monitoring
  namespace: traefik-tailscale
  labels:
    app: traefik
    instance: tailscale
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: traefik
    instance: tailscale
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-tailscale-servicemonitor
  namespace: traefik-tailscale
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: traefik
      instance: tailscale
  targetLabels:
    - app
    - instance
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
