---
global:
  checkNewVersion: false
  sendAnonymousUsage: false
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=WARN"
deployment:
  enabled: true
  replicas: 2
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
  podLabels: # Tailscale Traefik instance
    app: traefik
    instance: tailscale

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "50m"
    memory: "32Mi"

ports:
  web:
    port: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    transport:
      respondingTimeouts:
        readTimeout: "0s"
  websecure:
    port: 443
    http:
      tls:
        enabled: true
    transport:
      respondingTimeouts:
        readTimeout: "0s"
ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik-tailscale
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: "traefik-tailscale"
  kubernetesIngress:
    enabled: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerClass: tailscale
  annotations:
    # Links the Service to the ProxyGroup
    tailscale.com/proxy-group: ingress-proxies-traefik
    # Sets the MagicDNS hostname for the Tailscale Service
    tailscale.com/hostname: traefik-tailscale
  labels: {}
  loadBalancerSourceRanges: []
  externalIPs: []

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    # Latency buckets in ms
    buckets:
      - 0.001
      - 0.0025
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1
      - 2.5
      - 5
      - 10
