---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-config-secret
  namespace: immich
spec:
  encryptedData:
    immich-config.yaml: AgCchUGOSOJ63POaSH9Qzn1TtySkedvAgb84eNCxNfxJ09ZCFLTCW1I5Xfd+Stn73KQq7sradC7ET7QFEP+uWEfByKJapDazxWtbC6w00XSB1b2MXb79S4dnX6imXHoxZjOjiEALDfgtxdtj3pZmVAsErZfT1Ja92yP1y4T4s+f0aLifNTkRcKOLt+YnfieiKSCQN4lZ74GjchEmt8Bpaz0loTuVpyqFbJng2GoFRsq3Z8WgVAlhfVdAmbXmRUGQKHc+sOiihr/OALpmbibVFJhzOHLBOv4FWJ+52y5VszrH/JoO8a7lGPXBmcf1HjHkWdJzUkAkwx1dMk/3cYeDFQMDVFn3FURLg/UDucuyyuCEEQLS+FoncMqn2MVg6fbWZhhHYpQMY16nHa/x3oLQDs50OvOH2vWnGAtASxRZvEhfFmR1sOgPoqCBT2g5NDfMcOKrQVR9AS+i3pP4XWZBV3RztT96XjFCSivTBQKbcI5Wa04HE+fDDlcc/dMB4px1HeUOP1KEO7cnIzGSJuhdwZWiMO9JssPpAWmckHIlubro66SuuYG6tEiAghNzVifOmeXkNYVaE/nZfHUtqGHOglPl7Xs2ITQEMmRU8hV8JvNjUQ+4MCS0dUQw47pFOCfIGmeXMp8gnJnSwVlOpa1K+UQm6ZIoelGLH0aFN4aOXLQdK8x+9nC1fPqgX5GnoSRewK9P4lCLivLLNdsz2IbWReII0+rXGTJhg5jfBAEgFnmsCoaGAsw4oos25Z6kIF5uzuna5Vny4i+xJcLEabFvutunzk3fdl2X7gm+cD2pUaaMeE2dP6687KVnqnQpDZXDW0vRWURZrFUizCsYzLRtRgNQA2aGxpp80apmIXlVfzZliamy/j+xOWDHDcwyslMSRKq8Zn0vZdWfQRl4QecvlDM4zEWkNfwanSxncfb4NSuus4tPDuK1JzVrbW4W6v+zfg1ttQX1irSqSKQHbVHeRCrrrPsobeFzJYAATvpI8SZ9JU0NRPUVMXvrbNcFfULdGtbjqpwmcjm16kyaTph2iPu1NMhZ8aDXRMI5j7VjeJAAwpUcaepg3v9YoHxh+LP7sGiG69T4GfDOeCAAMYlmLh0072e9/ga8uAECag==
  template:
    metadata:
      labels:
        app: immich
      name: immich-app-config-secret
      namespace: immich
    type: Opaque
