---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-db-secret
  namespace: immich
spec:
  encryptedData:
    password: AgBd2h8PrA1eRQREBOFxi80FkShNNMdzJTAM9uC8AT/V0d+fPg+/6MPIurxPXnf/y9MoNW4Xu+Hs79s0fkinx+5Y1PJvWfrMKPfYcpvhZcAaG0G+YaODQZ9tBKlw9XA2lY5vanzx3S6UPucwTF4v3TeEl5+s/O/DNDduI2KMHysFDBML+Z4qQgapHYCgbM0N8E3uvx/xjwT6HiVCpnO5Ne9mXPGl/pJlDxbj8SkyFC7QT4vepUdsjuYwTWp+eRO7DAUk7jjwRNbt8t70TZ+8mJJxEABHg51/omxi1jcv2SGMTEerl5fwTlivIukTr6BFqeOrJVnwccg/bGt+4zwgO6XW+/qTPOcEUmwMavBy3KLsAsRNm017E0SVn6rtMx/6FC0YReKMWlRyDdZfGlRY+zMFzk40fdVvArmHCwQvEHvYevZ/IzuxFyP4G0SI/p/fxfblLPGpaOrr3WbXe4oih90hpNiW26a1amMxh0BdjpbFMf2TTJnMSZB3k7vztLFGTSIQSXgO7GbaZo/2olm8GCSbFmyHLnwVgd+u1ceCogBs3byxWOglLm1YnOPKhKksTXgMVTvgR9e35lqDEHLeoCMgZ0+0/TRrcYtyZRzxIKAzbPc/FRFBc0EdwJA3K0olUh6tgCWBsEYwwwCgKd0SxsVFIL19V5QFlHVkqwgPu+YpNVmS8AJcD0x5beP/prdXhp05u8UCp6WVyLpekvPBRnePBxX12G2dfktkNzpmIjePZQ==
    username: AgCwK3i1x99K8pLY/nc3EJ9GZ2p518+qJWeIZ7PceMDu+45h5jCaACdNKR8ujWAXlzCru8c9p0S6Xlzfit8M5aD6sNrSNgZf8WetTAqPoCwBFr9DH7b2CdAK5mYrBvbOwo089caJmx4222wyZoz4Ejqynr3I2sDyafjqSiYJ3Cjs97mQMzJfidaDllouS69aFRH3Y0P/9zw7EX15bJBfmY/mKv8SQJZ8JVlUUoloddfj0YBzVe9lWmu48BnODgEPpsnwIhlrrnnV5MSBM3z6mfYrBhtQPEiOEdtt95HkQcTVtMynciKinnNv5eivtz94zNMya6clqJUEf7Ozf2ATOtroRoNiIMrSO4uLm0EhtpTX3SrN+Tb6DNICvknDHhiPQRc9njJddMzxnjsOOlQoLzfLRXdsBESgQprylSG9AKL26dkmfPVmvW2xTWlSGqMTcCAPBeiu6z4nnrQ9MpSvnNNIPEoCFiEKO67NbxoJhc0dsb6R4uFiusFDYVyddCfVY5hxB2EH7lRqPqK7oMexII5wUTwM1WdROSv4r1MZLBQAxn+SxgDRvtMfwoF0eNyRFxrB4j/cjFRln+xTkJt6NScmPSRs/HdS+985Jz8y98xj/wbwtZutCeqp5BnOwWCjoM9lPXe/xGae1+2/b5tp5aQ0x13v+JJFjas9flRLPugDLAyUha4nrEgZEvNi4aRKnxc6v2fFOJE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app: immich
      name: immich-app-db-secret
      namespace: immich
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-cnpg-rustfs-secret
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBo4EOe132RpQL7KLbSnemHpBf2LYWm/7S0XTtqJMzbc13/dJZy0+clM6EB0XU4Bs6Q98RCRzxDzbE5eGOGNcNI+12cb0FKNlya1BLx1S2EOSLgHAbT3qIm8Whtl97yndPhjBCZ3/riwNl6umRflvM3L8GfArOJYu/XWa0lZI7L2aY7poipsQXszbG9DquC29uLfD3pA/DeNVMLX4AjBa7P9ZSmF/PQuc8W40k8Zygv6Ao4PNLFjg60R/GJbJJC2jYLRty9McMyAdCSu16enLcTR0CvDM87yHcSyitb0xTh3Y7I44PHtjHC9QL6i9275dt6uEhV447CrXiAyRWDA4foHG+7vSgF8exFG6zq4mjQN2bWbkhUJQ4Z4ivx39gIE06Y3ybu0Dr6JNcaVEnfyb9g5rIoW2sedW0I/ll+MLAxQBDqLuGidYgYRhYIUOfwSjoUJm1MnuG7Q98zx/AWnN7UtXWarbBs62mPCzVG3+TkdkR2wIXWYIorDe0NOg8B4mDLsOzN0sJjyv8TlKVdG8VBbfffl4RV3xTVf6vAIdKNPj7RTAHsw7U4kVANvRD55akGhvrEXNAdt0QnyFgxxIT+4aTDWh7rmLCXPJtOAxCOMBf6ynv4aRE4BFpG+0K2Q1DotEAaR09p3RhitAnT9N/edHTMukXIpim1jakdqkphdiUbZwxoO+jKl2QHk3IuyWnj7KwMHV68M5TsICk=
    ACCESS_SECRET_KEY: AgAeivy0FuzZyfVgmC4WkMtkRYMCF3fVas7v/EcHJOYGcJBnQIyEgY33HIpPHYXnHX6LifP1k1+9CSTjkQrXZQ0/VjrtMTErxcaDr3EK6DkcbqfVH0OtlyIAnBCaUoHXkhjgq58f/VFiiBxwFM7oG28wyigwSup0Q3EJQewAfeqzzP/hNHntJmH1yp/z6+H34oTFV9NAG67NeTl+njhEs2OG7JLmJ2WVyw8zxSHauM9mG6pE+12edNUF/PtDtfSH1cJRIAXwI9wlbuMJaCgt4UcpFLaFuKBl0+hQ+PELCUgm3EtAHrcUByS4UUyUdYxkDCEb4N+LJHD+BnsTEh/xCuUYZL2CKXdTTPZ5aaXPkpe7qJ3BKhKJ2AmlH0+z5q3nDhk157pZiiBmr/EFHHHl8uFKrJ10QSUj46qNCAPRKviwYD+Y9s0NetBWhsg7M57jlDJfGZLJ8KaBE7fSFIBD5OCNxNIUw1q+c8F5bXy82yItSQtx4hZNvCNIHtB8onRfPS89BSwgnFnI1DxoR0H1j22M9iOZ2XsxGEqKuBM0ViapXFuA+IRIL7N0azfLQ98Qu9eNIPPd15OaRYI+Qsq88y3xAKRrIqNUcYdltdDkrlps2THeVm1lz8rGaUNEwMM/k3tJ2NDJ2njHa4SBnSLrMBcAKOCwXZwb2TqOji0q6luI69M/sOJj1RNLh0u/OInF7ceRX2bVtz09SKwA+htkiUpZVNJTuw+50orh+2E1Rg9Ivto4tSCulx01
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app: immich
      name: immich-cnpg-rustfs-secret
      namespace: immich
    type: Opaque
