---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAPIvyNIZeYbc/ot9v7UP7wyhALXMui/T9oZiAmopC1O8VbB2+1BaQFheE1d3U7RoSZqP3qHJOe8ISS3IKZxfRGEKdbFWAv2+dKGWy6TqPWbb4HvnN4LqCdtHQaO9+E35w1f1J2qlvMX8PTlepqJK40evXRa6WVnMKTmr55WIz/3YvTNlp4ZwNHlOGz8l/gaYaMT2ckpMAOTrt9Kc+2MUSglbOrZ7aRMaHL7Mnq3N4hGE7tqbdquZ9qWpKuDVnU9WpDXpAbE2S2rK6swFVOv9VVHWAS6BVHaTF/wOASJLAZjBZD6UQYU6DaqcWlZ4BJHkFaIrqOc95H1T9qBiENTaDnQqFiMRJupOM+lgJNha6OqWmOj/WHqr+Kj6lYCX7RxisskMdWShL2lf60ikYh0HtXh/ntRWO33BLoMhybhvPyAxmQ7HX4Ko5T7QmgdYReD8s0jLWFmPTzyAXYWjenlicxkA4OglrD5svzF2V67aB7UiJ21ybS0yg2xdFilERWyL/jy040pIG7XFPhb99g5b4ATU9TEsdhQErLdH9HTtu3DDVyte5CEZkISTmhK2OuT4yjdKWAeyr1xYZbYpXN98XI5M0E1Wc3Zq6+AaWTqlA389WOsvBywzC7Zd0de0KJ9OQypEN9PVVxqtav1c8MYFmDXdJmfkJs66gQ/M8j2S05f+wI8bhNkmMHihyc1OVF5vvY1KSLJWpDr7v6iUlR7AG7e5ZhNJWoQHQ+wPbCVl8E6OJGE8unzADa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
