---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-secret
  namespace: monitoring
spec:
  encryptedData:
    chat_id: AgATNN98FUjVIrRVWzT7LtAbKONboBn+SpjpptMxvkM/r5XRuYPkVfzyz+PNeSlpcsNx4BEK1dz5muJeH3j9JbbAuimnjGEZCwkwpOL+yJwpPhMJ6XcBT+P+RWVngzCgk6Y8Mz/LCcy3Nf5Ky9kSurV3LzXxnkPh3TLciwW90HVKzn/kSdd5PNf8396XjdZVOFzPOrFWO4WKVAz8Dn7DOezDzNFZV+5zHcnBtggnMzTt6CWmahYzh+fDYNhz9ldEsG1E4Mn8lE3V4th6hjw9Lh7FT/nGuvFIFKtCB9BeX4pRIj4leYv8ZcCAI3VjDhpZiiZ/a5kZAKbrX2h3RjHYW+kbbdTL887vShiC4pPqCq4uabTLh7VQ5DHRRPI4N1bwBwk+Qr30PSinSEIqt50dzaNlXuHuMX/yhhPaWFl0QK1xMs0feU/5QxvkxzUvMOTBj5nkYlzrkjum1KdS0RJQva2w2DxF2TAR/IcRxnXWuD8cH6xnY3Crgo0cDW1uufWzdAVnPywbC/drzBHUTaN1NqeLe9CWiahYbB4NUhw5bwjECf8q3V14Q012nsxQqHB9fD3wyp704j+Z23nB+/iKkhYJ1S8WCYAUfok2cCSI7cxoQ5Y2WUk32H8UgDToPbTL6IB13tfmsi8KqRfJ1LUMfWrPSvitxhqCsAtV68yqqMMkvy2f7ryt2dt68nSLYhne0/VlhROF+HDgK3E=
    token: AgAJ1AfphGWz1WB7dHAhie3PVgxyt2JiatoEj9T7ZoW0Zwiaoa515h7KjrztmQD2po5y8l/JoSLUJJplCW1QuwsEsW7sPiOVxBLNQ/sMmSvsJWAFkzzZfuYTmvx6og+q247yv361k1MlR7WASoqsh2WXXK9/MIUf5CCXq1Gd67KmGaSgeiMw2YjA0QMNL/77jjl3wENegSzKRxikL6vNvI/V1edCtkbpcJGg4loRjlATW/Xf8tPSaYNIV2FYgCmWLoeokvCWPIkeHsx86fMiTi7ESsVzcXbUdZVkYtZCyRxuB9+gc+IMu8ej6GdbxK/gmgJRMo25v+4O/Fhs5ooKNTBrNzxTWkvm94r+4OURp0DXcmvogwwqtivPRgmlYne7BHugPc0EE6JisCX68RAulslKpZhwCZ3KP41wWLtRY9UX0zvRHucpl3Mc1B3kB3hY6atEa6OnxPWIZrCdoLTtQHvFxyY7oGmra+I5juScZ6DHTQoe6VQ3demG8q0yIUXX/570z508zOfqN6yz2biJCHlZDoLS3HanMWMJR/EGOjXXg8BXwrZTWNonkR07Uk7sG6FvSPCd5t3TdGm9RMFEalJ5djBE2vruce2Nu4anB4fD95aVfEeL9DPS19D8JAFZTjcLqcfh6POPG2lWfR1WUVZJ5wxMt7dcl4In9RJa42KlGPznDwmklHViKs+wjtONV3LkP/5tRwpxKQL44sz+7qKUKTSFk3FD9yefGTQKPyhjzlVuZ1XDuTxO8YNJ29Bl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: telegram-bot-secret
      namespace: monitoring
    type: Opaque
