---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3
  namespace: monitoring
spec:
  encryptedData:
    S3_ACCESS_KEY_ID: AgBlvRjxLF+GG1NNKQmq3IssE4ER8XDU962r6MfU5E3R10FmQOdSgs5XeJ5K8Qz5V2jjbT2BP5J6EdUUiD5EPv0Bl/GGfdjahkpfACcwHxs3TMCWXcnFJollB2HryQmpwmqAqvzvgrgcFfXYqfCxaOft9/VNGbdWiTs8mt46HzabOegNlewqJHXgrvH2TjH4xX0Gp3VtI9zyozmXZA+GhNFKPHohtC3LTMBMr/hpXz5n/fuq14tAyfWrthNtdAcr9h4k2LWsHQuRlIsUGW3Fvv803dtWhjj81IpNc61RV4gu5IrMKdbvVZ++yEdiYmZV5m4UeHqptPIwqViDEI04f/Dvs6gbzHqUNrX+vCc41H7W+luHQ+MqvLjkpybWBaX62NEBPCOq71oiuDyX0/QmrO1+rAB36EpKtAooexpSpt1AYnIhgbSSSI7c1fjlvxXYSGA4fahb2Z4CRSCA2ohDLfolZCQCk9StFZC8x96ezecSJ3qpdCEegCgrdVumG8oPrbKeRDm0JRXWZMoPJr5UTiBDqzJpmolQyA2IlgYU8Mo4tb9Pm26n1pJvpvZp1/HSPgAJggTsMI/+AhVAJFyCCax78ISBRMAKvPeKHqEkq+Ro6VmauWv8JMFZ1a6iMBSUy0CoxDslIYlWcJcKVJbpfmdS3QYCeqpCoTpxaD+W77rYa1ZNcvog9ISXJtNL+OsJ263emdZUzPDUqpkg38Sba76T9KhJaQ==
    S3_ACCESS_SECRET_KEY: AgCHoUPnDbIhBNZfsqxtUPBgiNVLd8Y5990SNKEXBcV1qBKQZRByIXS4da8yPjBLabxCOZFLSs2YnU675YfmUEndxNsaf55AmeAki17350Rwt63Vo1av9mxJ0VtoBage/xeqKQQ8SurizhDyNXTShrrjHts5bRaP1ZW7fRgtRs/YR+RmqU8yfqoZw0sGTmxQKlu+m4QKhOvmZFghLcBIwYKO/zu+/GB7m/AziADaGRdq0wWgouJ1JEcHBwMBqZ3el1HPVmHjls9GbYUB5BGdHtQUYuFOGrBq6r5VJOmOuelCJk1SYnZz1HS1/gC/2f5qxMw7tIrwdwcTw8Yt4FbRXXko0kPXzZ8wHF6kBzooCuvskWI6OLWN+04unaOztpS3YnZxlpwsxs+vE+Wibatrj0tnRgOJjC7M4jTdrrqr9BPBQEi7FS57DyP9XPNqshPK/J9WOh1y83QmQQK4L4rTqTiS/oPPcYKQc6s6k/rkOyIgM445UFpAbe236sKmx9Y8x7fkMwGWi8YUXQQC0Ecs4NDgc9wb5COCkefUP7gAbk+dVaox7Kj5o0UUuJcZGRW/o99vGoY4/+ueUiZXHQc9TcpDmCPUqXl61Hfwq2a2f/1leJ2LY55qvhr1QRLt/AL4q1q7H2eFheLTDP2KPc8aUbzv8+dSXB7trmMVqGNH6Fv/4TpFA9ghTQQF8ts7RqSQq2ntPI40JPOIL9DXN6Zu5yaIPKrFFSyb+YebZkcG1JNyQ53V+/8NHsdp
  template:
    metadata:
      labels:
        app: loki
      name: loki-s3
      namespace: monitoring
    type: Opaque
