---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3
  namespace: monitoring
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBNXPesRQfdhiw9HPnoljiSpwVR6VUwlfGRKjWJiI8+f/VEDcaaNt3aKLzxmUZfLT4Xw47zlT3Ap6IYZaOjvZF4PqCT1iWGCToye7/2PndNy7uzcjFTTUUBlADCxjLrpA+yNsTxkfvBEUX5zPwELdcXbrHt4rgwPSbkQuldohCROoWAsY8LrCrT9O/Lm268oTavDOMIQ5vOr6J+f0n81Cy4cn8IyLncTdU0DyyB1AIyTaQqHGqtQgCAWHMnBIghD7eS5K1GMEjNMmgooCYuC/vIjMOVHGyrEWD21x2r+irh8kVVhZ7pCrFZt0mcv4V9ewv0cxyU+bH/ZEJ7GrdijYHggzvFlscLx6n47uer2Ib05h1UA01x0cXUIIXlFBsueVxBeeVnIe0VDsXqhS/DmhMHE258Qb3mOY1HorRBCUmVsHdvilTcNsFo0AV+tZ3wl0sUkN0puQDHvS/UdFAQfLATRvE2IeoqBgjXfR8fTUkOKkgrGga+vxl/MRXgSLDHSek8W9kkF88jXzj5xH7VcNJKO1SZ+z1+7luAjG1ti92LTcoTmRJPLJ+kne4d22Ybg6CZBVbwxaRYMIfj7jPvwlGLVyStOtBQEVs3J2OZAkzY6Jsatg/ateuk6XWIzo13M2uUeFhUbcnh39om3UBQkvepxU1N5ucmSeOiiezOB0haOA1lAZRpWsSBYR0TvwqxBKivq4rDbN4ajmXIweFEU+pEeMrqsA==
    ACCESS_SECRET_KEY: AgB9IY+33VHhlKBgkucHt44A9NTLP+IauMjVG8EPN6aB5WH0uzDIDaEBoy6MEle+6kyzjM2+lEUIgjiasnG7TaPqP9yrXmgoJYrji9zA68aPhvBZP07DZu0mNYJ0yzFToxsOXz60hdgwF0246nty8v7R+TWli1eaNXaL+KX0L+Wzi16rNXoDj+uV5g/SqvavbwjUb5X7YRBuSDlr4pmwJrdx6VPi+3tu6D3YCTqXagLRF+Qyxd693Xn5DY2AfuChCaYc1GNrt3mOsDhcT0ZeQaZe5caQ6aGw+jWcljN6GzqNE8q77ctWMMNT6Pm0a39RorManZy0p36OzVxnQa0Ky6rAvUX4RfjaDwwHybOa0nABpdd16Xa6vB++M8DY5B8yCdx2ot9cz0GvG7dcafc/VQrZR65VwV27xtalr01TNgFglxLuUINExGhHx174sw9ci9R2oA10i5q4Suws8NqP/x0aFMSWBnG+bt9iOrLCWiFfPib7Y/74jhvqOeW2FaCPoJtDRyhFeY/qznCY4WUj+wp9ACIJ+MeEZvIrpayACKim8+1JkOUc99iPLPIDmPXfzox0GYrRi55B3TO4blaN+imnWWufSHKLyE1yWrYl0oMPUUhsgqfaWI5nEZ4OoMH1rpVLbyGVfCVn9j8uqERuhaUTLwIQUzTfg3E/PAK1UNuXKP17itY8GCEmC8iRkLTJcyTUGX7AJnGIv/wHxOjMj+GTt2xEi9+9Yl+0+BIhtHvDUgWJBwZfoKDW
  template:
    metadata:
      labels:
        app: loki
      name: loki-s3
      namespace: monitoring
    type: Opaque
