---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-app-db-secret
  namespace: sparkyfitness
spec:
  encryptedData:
    db-password: AgAnafiNu0DmSwhp+eBnuiF1Rzis2uZ8Ih1DrEBUKzu3IHLc1R19vHiqL7AWwI9JuA5PFVE/zyejX38I2D/wb/4FhLomwyu5rzfInrUFOE1c578bwmH+JAst2J060a2anMrNU3cwBf37mjIFrW6mMdQTnh5RotLjHF2+6uRuGirOEufmORrYMYHZLoBB9PsyH/e+kLMrRncooVqwrVxkDZzrA2DJJTjdrceLPP3ssQFRGcmvXqYJ24TstR+9+g6VcYvJu/XiCR317sLcrG4nLbzZjrMvb836bk8bqV+vEvcx4mXxHTrLs0zgQ7hF1McnA9SdbtXR7fEREXedxKWb3/ceual6CgRxTLmoKoyoIqzpYJ9qQV9zWrtPlI174D1VFDFxJeT8NjrEAEyJOAdyPMY84ezAD00rvlwgCSJDXS4Ho8NAox5+9zf8q37PFfEG0oMH8XeynOx+AX8qcXIxk/anh56CFmnPOpki+qzQzEXXiz6EZS/bVpJ4Z1PWFbLBDLfePjbO251EQyu1gQIFoeCWm4IhoibR7zcalmfFnwH//M9PaTSfFQD6HIPXiRs/QhD9jcUdQ1jIpEHJrGz+rnYoxzexv9iJXpM2gKp0TYZoIxeedJX2ZKEFMemyiy0SrcThcvmO6sKX+kCu4QVZHeGJevLK4mh8vpkZbld9dISwQFaKmIB8h6gc0hfcN6twIRr/wUTwMKKiLkwtWLXUHOzFW7WpN38EWWh3XPYzmLq+HQ==
    db-user: AgBwJQL2OlnY5tclhm+k8NQAqZUNGr18D0dZLyg5N3594XxY7CSQtLX+WxpnX+St+/7NsLdJoxUSIP4oQvsnW/4tnAt1QIxc5aC2XU+rUvRQ8cS+KGFYPLxy3+Ikxb7zP5uXJsBHzzYRxDCpnISOOlsCIng/7AWiJKcDey5Who/mj2Q1MuwZVEjRpN5+7pHNWMJh4LafhneIbzRDbVQPrQ/rNTQzN+aJWlnum+d98wvAjuMMz2YQLJwH+hHhnFqosZKAt1UMD3KA3H/ao9w/KdpQaeQQaAIY2eq5XFg6RShWrndOODMSNKwxPSe5A7JWZVVHv1l2wzVxcFj6v2pfIEtwtRLXQEkCAy/ByvvRZc3OcQJgPeR5nBY6w6ceBmXdsOBXL3MmakYPC9uVe0Q97ioKEQxx/Srbse+tXkSfYJ9+P0YLkcepV5DvqP1yuG+Zp5CPnGwMLfbm63qizVWSY0XpcOzSU8b0DeQnAri5PqD7P9XFnMYgpwbSoF1fhdQkIJlIGw/g0n3Ut/FkD2aT0h6LXw/mOyWMfInTOVdgcsKa8HDLuRgwuLQfIurcFeoTyRnnba/O0sXLqPmdRviPPl3N1lpvnznMcOzVvU9e3bAFEC7Q1Qfg5C+/kVHY2Q5pgAtmA0XeteBe99sxpA8ZO04l80CBU008SWs+gIJ/7o4D4rLyHPC7C0iQXREDYlf8/rUVHTgToQcNVt8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sparkyfitness-app-db-secret
      namespace: sparkyfitness
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-secrets
  namespace: sparkyfitness
spec:
  encryptedData:
    sparkyfitness_api_key: AgB4BGMtfWek3FPcyJNxcrGltHWX7M/6ZSPi3mEQGg1NpfU30Hkd56VSqZiHj1wKl49+v3trp90VMRvRuYGWBOqsCkTXQDHzIlfQfkCwvMHrjqxUp8m/amFLrou+mcNnWoB+lGyRVPeTBO/CL0oeOgWVs76aSpZ+zYzh5mY5q0DBWQq/w7Syu6gDGRc0GBS08j87u0Bia/9Y1/CGzVr+wUhX8vuU8wKyF4PlvZeebI4pqY1w38hnOWQGGtlqNnT/8wxzGFLj7ZMFR3BDjYf7439JtKrcdj924o8yTb6ySOULED6JkYdhfRNo7C7etMZGInliFWwPsuZp5taRZJT55smI8lU2usLpiNE++AboWqpV29Tz1TFfkyyAIbc5yCvnNQOBdg7iZPFqEFNskRc1ZpuYtDcu57cOnfnMLNK/coSszodDYucaT/MoZmAv6+6ebk8XaK4cDlxIGFHeCU8HUOhvrjZKWFesHmDiGcZvShKtZg7u1O7LYJnrtisXWBxujeOnBXTMWY0mlWejRnloERCscqDXicyd2CKs2Wfgccn9k8uv6ncULY4R2g28MBB69QlO2h3m8oVGNQnoSrSAZguSejOQLduO4GoP55aMIFVjAy7UDwOqrYVxt/7L3wtS7G633OlYPhxvuRXOQAzakoQGUElFq0NVSdIuc0F4m5nRHJgM5N8TWnMRCCaxcgjhVXIKoH6zjzqSsuFOVPmj+CSYz5ogy25uu3nKCI7o24AfENcWCM6UUlaPqDE5c4Mx7cG1tD/zyM3nnvbvcE3LjA8V
    sparkyfitness_better_auth_secret: AgBcWPpcHc8kV7myn1omgG47pH2AXfuPkucx0xXNPWOtOirHJTuNmeaC+j+kNubWOwM+IF2wMAQblM/oproaW3YRO6qvq9HASSrhXNabW+W8S+m9IJo5Gw+JtvwNjbjvCafDIif0YuNtVKkK0H0G0Kd0NBFAQUGFk+W72912JqP64xSdDDngLqgR5VDOe1GH162DlTAEjY+FfXnhH4Kg4Pv3Nj81pFBGhrXZOr+FUQB3NEK9ed5g6TnWIvJsOquEetnJxWIEuOXiu0JbUyPW6omp0byRzEp2JgE8DC9cE+h+N6IgJzOEmCIyDAay2ID5XAZQKo13wyrlnDPD26mMAqTs5K7F+aHrgY06F+STYUBdXc7M6cZezVIGo/7Wi1Bl56aRk+RT1HAzHZ+BJZV9NOoTilBSVK60IsC3FQoyoIZWbkWY2quEO/czJemjNZGvSTnFtuG33mTSTN+DFNSZrx7+oYhW0+2FCs7g9iXR0anyZ0yQYtF5Rg+2agGbFDsqAyVlNHkxrTLMPeiRECp6cfGwElo/zZ1ftalHHRY1/zqsrnrMUao3LqqYYNfXQV2uwAooTiXm+0mibknMCvln/YtCQfODzyHbaeAsBjcW0tzUeFBJHaKh0VEtl07hjekNBKOVIgNZltkPdj/96xS1XgDOiZP045fAi9sDisp4t/nDp5JsSHKL4uhLm8rRwRPhVgaxoXtewdYgY7KAcxoxEq+t2gVnXHM6OqrP8iKUYoiD/Ux1hUB5dBtfD9kIOgdpXFvjwHehIXkFwdgWIeXZizJt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sparkyfitness-secrets
      namespace: sparkyfitness
    type: Opaque
