---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-cnpg-secret
  namespace: sparkyfitness
spec:
  encryptedData:
    password: AgAHpPzMSjWQLoJE+/1HspNWPOgH0w4DAaT3Aoswj+YkZr4t042FzyMbc5Y7crj3Py2cVZ8f+OKJeTQDhqFdfw6iB8z2rCLTrP3/yBhcKrWth31v+etOBMvKPEs1d15NyfjpsWHF3nqHbPjvMXlG1PWQNR2B2NWLK+HSBT9JCOrWZLyTGsyTSAG6ivywygHA7GsItzxB+Pmm0d3T/S1KjC1X8HNlmABmZcNAB5KhRSv9BrDByW9hGC97xYEDfwQC0m508K7P7U+ROxAM376dnXFB0Y8eEJHmvbl+ScHJE8DgjdfgfnENkBPa/u0M//xgh0V+3V6YnZSuAD82o7s+cbcpFy1OVMflEzIhMGtQnSAROiivCxhZTf/yAnNzSOuyboUetxAQeMCj96SQMtBq4+e+tYz2fu2raT0luLrXJ1JuXl4BNUJ8q0Psze9tMwcWon7ItyKKZZXNgf8lxjSSRGkVQZac7W7KBePaViSAeUIFqKUSg5BjZkEKHN7VenKVL/buWj2QJgB1PGvrii1IWP/gResNjE6R+xA9Zxd6ubITtaCkFbD7yb+/RTsgAlzcq7Be/SVoJ86zwvcj53s9w+rwU/ptZMXayOgJc2yzM0jswuGcMuVGJ9OwTUkD51/XgDB3kP6xi/9zncFla4CunMJxS28kO/FsEPL6Z0G/EtQidY+/Em2jVpYPjPlh4LktegckkcbLynSdg6ovl7HB/64Xjo890VFkNc7PG3UwY7SryQ==
    username: AgCo9C5Jlw/Kl9xqQSAWNUrt4B9H1V1TWJnSWWaF5JyYX2wXBfxCXgeL9Gej1fdq6yiDuZztAh8q3dyY+uHBZgqA4S208Z9IHEm2gfZzYeRREWssyGyQ4AmqwV4xZ5DJt2vEGhkBGKAUNppzUkd0oeG7NeFF4NR6bEUyCFwfAx20tfRjbCaTr8gZwmhvKY7zQzp4ET9kxgTdRUuF7GmXUQZlhd1+SrKkXg8jwEksqXHmdJ88n1huXZ8wh6fUWHf6fTB8JHww1PCBPnVYtNaoGtsgUgA9w7sbpiQAY5/NrBq/jNZ3laOmnHuDiIHsQ4ghp4mrWoZOSchz3cxTAAQCIy1XLV2j2r45ajiWw8pG6F1TddYoD5ut1kxK6t6Z6KiIqYgCQ2nQnmzAp8DEBAxC+LKASV21lrVolrR6G9ljJ7+eNZbBlwbaqWvmIEMzE+uL8eqrxdaqRvaXiI8mjsmjwfROQjx3TeOldlqtxRS2/+2bMtziH9eMkzU1m7dJ+rxlsU6aEgydmNvCmEzj7NvuO+fS2JoxpwS68j7gco05TRU6emzR+VUNABwiT3OfQcMcrW93E7Bu5qApDZbV8uh3vMVc8kjAS+uD1ZYTz3KdH+rL+/orDXVA0R7QMvM50NQdrR6scvbAEudIz0b8Y89iTw9rW3NQKf/+KYN6GgYuXJophtEY8QpRMsKjo1/Ij4Ph3JpBzfF4R/0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sparkyfitness-cnpg-secret
      namespace: sparkyfitness
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-app-cnpg-secret
  namespace: sparkyfitness
spec:
  encryptedData:
    password: AgCBCc4eIwXjdylAWJnVcmoeYNVsR88AKM8RfCrNxEX8iTAw5+Yfpbyf5DoVRBuNV5QhUbytcEf0gYgFvdy2RMNsarMBpI0AaIaNs60hUtTjfn+WtS14/WbuHckQmLQskFdJwUXasAeXPKViiQAE5tTE/tERA8CE3wAcnAOBgrt2Nn/SDP5p9mMFLhJ7BahLnv6GHkZFaTTOPGpZSda12RNAPrHHXWn/G/1tl+NYQvvJziNJeyVxE86RMWkAuRI5oSoMV6XnPDchjuecYnYZiahfYw/N06WopNOn7nbnb6up9mxaVO5oXxJIKSPbxjJeDVAe9zSAlJiXeJ68Bw7mnRbVepoelzeD7BKqAfWEN/UqWcQvHsu6W45S7TimN2FCkXigI2pMarAFnza+Z6QMoJ5rlPmB4RGunUPJPM/4yaAILXbEl2C9G6+azzGN61l1YZRxfN7uq7Bf1KiWp3igtaGbjY96A4ku6KIQg8qJH4pw4DLhipn3HxnbcBj+F3Sjat7dA+G6I/YWm+MA8AeGS0GXGog3KzLAsoAGdobz5VjFLrUuZLN9yuupNCvkuwN3ihHmDpODrYPOrgXNbiVVKFVyzIvLvWQHhGniVtuVlp4SK5uwUmjZMdlLAoCz0RZCFCmPYhCFoPF56l3LLl1gRXL7evP2Cr+Lo2rfWT8DPtL1lhnZ1mIyFl1TG+tVuYDNjFmY/F2UOvteqxgQgzPutH+Q22aQrEnX2aoSzFzXurIzzQ==
    username: AgCVlyukpXtXFBYMYg9tgA8kA0wTGdu3m/BP3FI3U6Ii1ZZE/E9wKZZN4GUxJDIRVaanVUg6PZ9YX9QsVkWSSEdZSLlhzhyooQ4G0FmTe1PTYxFhGRc82UPlqcifcbaHynEeH1RxgXxYpNNB9Hb6Awzdx70rk+Np+iBrdajoZoxfGz/Jb8sZ/BBddcokEtVm+c6QFwcJfhYuQSVQwPSuwdP1VJl6O6jQb+G2l9NE7PWDj1QvM7teWrutT6aOlb9LEekbI+yqiZ/NXlTJf/rAbP/xFcwkP7+ZThekZNd1ISowU93B3zIE2pb1zkdlJS133F48unz6dYLa54I0/ABfGY62s5wcUtquyfJov1khxWHCJWDvt4TVczQOTxJVInRw6WQkI17Z0Jg9n/NbYY7h9KBjM9VDsilB1P4CmFJx4YNxLylCYdq8JmyoHs2k+mMfgcu2SPl7boLRkzLacYV02pSUR3lGgYpZj5n+lUtcsMBvIziITvxlM2ZsuMuK8ILQl0pA8Qe327EyIfKnbOfOI6gMyr0sVu2/RLwkS92I9WdQ4pFWaNeQSJGuw6LOgIP62+GGt4YAqMLslCbL5r3jQK189APyXp2ujA1VdrwnEruPnOAGTnmeFj6bQ6XrUMsUDNHsjAPVtZ0nR2OjGF/Ws+60glHfj/QoyBTH4v/ok7fHfm2FMXhu93KQ1MR4gR+AdGmL1BhdmrqQpSE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sparkyfitness-app-cnpg-secret
      namespace: sparkyfitness
    type: Opaque
