---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sparkyfitness-cnpg-rustfs-secret
  namespace: sparkyfitness
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBwGQ/znOa4RkwoGmHgKJRdt11os3xHtnjA2Lp9bDZpkz4hFkQfdj2EbQgiYkKJYfKPazJUdUnExsQujOsPrTHrSaHiTh+Mkw5O1EZDib5D3LjM/DdaqeFVQATyxiDkMo9cy9mgMtVUvjnts8sTyTEfoDQLuqdIYL7g3TcF8vtesle9ltb8gti5EsNfmRcoolqeolqr3f4S1Q6w2JN2p10Qi2fggQs8TrcqobATMsv+FHgAlqBdKpFy1nS+J8BZltoa4MoH3uXOegwnil6hQj0Z2Zam6846aajnYxVPz2ky2YQ+m4W414Yk5eCpyXBd6vIA1hLcYlVVG/Exh098xcJxwVVkHy2w/kSK5xPhy8Gn3F1M5voL+maBAbnEOK8sFPzRtrZyK+YMSstcnCBIhIopB7AMv6gCoMbdpw140oNIn5Z6hHT0RFOTP9xpXXFZFjkaaEM5gPY82VX5mmalsUxkK18qQrH5x/wMtqJSx39FZmBY+E80un2R8Npmjmk+5mZS0jTTTSn6plLtLKWaHmYXZl+ed5Hy+Kf5Lv9tjRWrZzEVg1tVeKMhWSWvUnubsZkOlITjKOdL7qzCbbJYl7aNgglDl8zFdqO1m+LHAgCLDSWhAmnbK5GhzknRyTVP1buXF74+nzOtzA39tS51tdjIWpI3aHMa7xxihN8nWrTgyFM9L+aaEGHxh/TxtWORxvkFEcmQx0PcdhW61fU=
    ACCESS_SECRET_KEY: AgBCjriDEkJG/hub4d98gjjAuVuFndYeswA+Lf3P7mUB+krnqZK3YjAEamixQYN1RuXWo2r+sgzq2ay8bsN08cgwf98iAG3N0IMkSOBjWZWTWRa80K7+7OwVlhZxY3Mst3KALMCtRBw5hdqNHk8YOhhJ69mX0DI7I9tkDz94tJJnror/P8hhiHSOMtvw59hGWU1zKBnkzEkKyrN/lV7q7Jb/4jN19O1iEOvob1sDEgvdSV2vnwWSkyPOJ9Ept61QFy3FxI0H1b38xbBZOlJRhhM6CI3i3cSEH1EAVFHTvPB4wcB18iyr+Y5ds3V8hqStB5v7lFzCNIFrxpdzLTtzHm5mxt87KoXIRiEO8wjalXFxWxMjgb2lu55uTKDDJB/DD4uuK1A6sEgRXPqWbp1vUm7+OW9BD+MHZb/TSj9+Sa3GJ/xNBzBTZKyw5sc1RIr8JuVxxWOnFHFvlHbt1rYet8Bg09CuXuI6a4o6aZALqzOK3OmgRy7G5k1dEQK1hknFY6QswP2MuDBfpYMeyiMArpAuJQUO6frhlXETOeqvI9f8FjxqfMWoqCTN5TkCxC8f5Ti45NtbhE4gA7z0N6lMcaKW3JCF2Au4eIZNkcTXdyUCYdZB+oySY6A2/JLc9QP0ClZDyYn8GY4b8I4t+0Y8nx8lUtJKCnBTrBu17HoWhqXB9wcryXvvR+xTIDUK9rqlnQxZPjOVgwF5DumsUrlt8fxIilhRCT/QIOWNa/8ZHqq/MU59t+UV9Fq4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sparkyfitness-cnpg-rustfs-secret
      namespace: sparkyfitness
    type: Opaque
