---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-backend
  namespace: sparkyfitness
  labels:
    app: sparkyfitness-backend
spec:
  type: ClusterIP
  ports:
    - port: http
  selector:
    app: sparkyfitness-backend
