---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-frontend
  namespace: sparkyfitness
  labels:
    app: sparkyfitness-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-frontend
  strategy: # Downtime at rollout, but clean PV release
    type: RollingUpdate
  revisionHistoryLimit: 3 # Only keep latest 3 ReplicaSets
  template:
    metadata:
      labels:
        app: sparkyfitness-frontend
    spec:
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - sparkyfitness.svc.cluster.local # Allows to refer to the backend as `sparkyfitness-backend`
      containers:
        - name: sparkyfitness-backend
          image: codewithcj/sparkyfitness:v1.6.4
          env:
            - name: SPARKY_FITNESS_FRONTEND_URL
              value: https://sparkyfitness.internal.dmhosted.com
            - name: ALLOW_PRIVATE_NETWORK_CORS
              value: "false"
            - name: SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS
              value: https://sparkyfitness.local.dmhosted.com # Alt origins, csv
            - name: SPARKY_FITNESS_SERVER_HOST
              value: sparkyfitness-backend
            - name: SPARKY_FITNESS_SERVER_PORT
              value: "3010"
            - name: TZ
              value: Europe/Amsterdam
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
