apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-backend
  namespace: sparkyfitness
  labels:
    app: sparkyfitness-backend
spec:
  type: ClusterIP
  ports:
    - port: 3010 # From docs
  selector:
    app: sparkyfitness-backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-backend
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-backend
  namespace: sparkyfitness
  labels:
    app: sparkyfitness-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-backend
  strategy: # Downtime at rollout, but clean PV release
    type: Recreate
  revisionHistoryLimit: 3 # Only keep latest 3 ReplicaSets
  template:
    metadata:
      labels:
        app: sparkyfitness-backend
    spec:
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - sparkyfitness.svc.cluster.local # Allows to refer to the DB as 'sparkyfitness-db'
      containers:
        - name: sparkyfitness-backend
          image: codewithcj/sparkyfitness_server:v1.6.1
          env:
            - name: SPARKY_FITNESS_LOG_LEVEL
              value: WARN
            - name: SPARKY_FITNESS_DB_HOST
              value: sparkyfitness-db-rw
            - name: SPARKY_FITNESS_DB_PORT
              value: "5432"
            - name: SPARKY_FITNESS_DB_NAME
              value: sparkyfitness
            - name: SPARKY_FITNESS_DB_USER
              value: sparky
            - name: SPARKY_FITNESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-cnpg-secret
                  key: password
            - name: SPARKY_FITNESS_APP_DB_USER
              value: sparkyapp
            - name: SPARKY_FITNESS_APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-app-cnpg-secret
                  key: password
            # - name: SPARKY_FITNESS_API_ENCRYPTION_KEY_FILE
            #   value: /run/secrets/sparkyfitness_api_key
            - name: SPARKY_FITNESS_API_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-secrets
                  key: sparkyfitness_api_key
            # - name: BETTER_AUTH_SECRET_FILE
            #   value: /run/secrets/sparkyfitness_better_auth_secret
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sparkyfitness-secrets
                  key: sparkyfitness_better_auth_secret
            - name: SPARKY_FITNESS_FRONTEND_URL
              value: https://sparkyfitness.internal.dmhosted.com
            - name: ALLOW_PRIVATE_NETWORK_CORS
              value: "false"
            - name: SPARKY_FITNESS_EXTRA_TRUSTED_ORIGINS
              value: https://sparkyfitness.local.dmhosted.com # Alt origins
            - name: TZ
              value: Europe/Amsterdam
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 800m
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/SparkyFitnessServer/backup
              subPath: backup
              name: sparkyfitness-backend
            - mountPath: /app/SparkyFitnessServer/uploads
              subPath: uploads
              name: sparkyfitness-backend
            - mountPath: /run/secrets
              name: secret-files
              readOnly: true
      volumes:
        - name: sparkyfitness-backend
          persistentVolumeClaim:
            claimName: sparkyfitness-backend
        - name: secret-files
          secret:
            secretName: sparkyfitness-secrets
