apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram-message-template
  namespace: monitoring
data:
  telegram-message-template.tmpl: |
    {{ define "alert_list" }}{{ range . }}
    ---
    🪪 <b>{{ .Labels.alertname }}</b>
    {{- if eq .Labels.severity "critical" }}
    🚨 CRITICAL 🚨 {{ end }}
    {{- if eq .Labels.severity "warning" }}
    ⚠️ WARNING ⚠️{{ end }}
    {{- if .Annotations.summary }}
    📝 {{ .Annotations.summary }}{{ end }}
    {{- if .Annotations.description }}
    📖 {{ .Annotations.description }}{{ end }}

    🏷 Labels:
    {{ range .Labels.SortedPairs }}  <i>{{ .Name }}</i>: <code>{{ .Value }}</code>
    {{ end }}{{ end }}
    🛠 <a href="https://grafana.internal.dmhosted.com">Grafana</a> 🛠
    {{ end }}

    {{ define "telegram.default.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    🔥 Alerts Firing 🔥
    {{ template "alert_list" .Alerts.Firing }}
    {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    ✅ Alerts Resolved ✅
    {{ template "alert_list" .Alerts.Resolved }}
    {{ end }}
    {{ end }}
