---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-app-db-secret
  namespace: forgejo
spec:
  encryptedData:
    password: AgBK6eWuV8oQ+mKBLkVouYoDjiecvlLOysqP9A5VcZnMD7p8gbs1bM0Qcl+wiA/cS2uuE0mQLBsNbqHMen0ETtxTr9Ww8NAp8Jk6j5TIZxbve03Xm/XLxgk3Z0uD2RbnaZS7X7lBcqt4aZmMPQpYc0fCIIQH/EfDGLiWsfMYfNslsuYBu0t91KjH4IIfRaEwK3f9TpDjNovI3E0JjqHnNC4SjmgsF93ZIxKNdXrZeCyOxwz1fR/esNrtpu46vniiN/nctumya0EC82V0blvq8Ok2+zNzRQaLlNs1HqE3A69/saj8bSZ0zxeQt2TPcKFu/UejL8PZp2MQLk5ZuU0Yj6JradMO5+gTmClKwdckxkt2aA4D6aeE3QggUy7/9dyRTfISRBa4NlBOY+bvIPkKB7SLw8CaJcuur+J29F27uDaoZpqCwsOiY3Xc8bi+Blq2wZep1wgBwuuzh0Z+tc1DDKjDWBski9DYzzBRPqwDLZS3PIIuOI8W5jbZPE0rJA3oovaLPZQf89L2kuwPaQADcD/i1xb7Ved7WnUgbcFggmUcb9Ny+TNjooBblG+xWdyKhURF1CvlbYRqRgoJEVOF+2L75FNpJi8TEwTQdspVEyLKmurqD/oZ0bsEam3dusOHUtBiir8vJC1jb+l5A5AO0oNkKDw5aZEaFdUI7ikyMCdEC0MQE+ld7bSDD/mKcyF0APNnAwwuO8zRdUBcoaFrbRlRrqeM5J47iurn7+91JayktQ==
    username: AgBFlCfa50Pqg8Bh73WUQUOnWMFCLgr022F2Jn2/qoVVDP1D4IoLXOuYN5XAvuleDWgvvRgX5oR3rchHY6l77fcvcanm8pM0/SaDOSIBo0MoVaol/sYFE/kTlG5txX1GRSUOmKntW84qeDWKl6nXmAkUnOFBm8usy/opn12XX+oy9/pez6xexZ4JZQqw/yZWgsj6quJdiIcWdn7pjd81Z0zO6J3szKpw7BiZO+Ytg5B28/GmIn1k2zo3eK3teIWNA0HbZSYFwAku5cDxusWeYHpLavZHHSjYQIXoWOXPi633LZXrXHplkSdeKI3DsU3MKwfjvZfyFf6PLIG9LMH3xEL70GAHDkiCFF7PiE+mCAh5WNmAkFwXhmXqqoQXIAJsPjrIRgEiNsC6bA2W2lHBf2VQ+NZKD7hJ5uX/JHxXT+H1Lu69/dv9sJQ9hB3kj1QGU/C0dW1VnHfMtBO5mqqC5gnhZSbVP+KnFkMxJSCGg/o/ERrXGrRYmJm3HWROUZYD8jYHI3bceOkCjPP6E1hRvp6n7SX87VVeQtrGiccZBq5zFCcuLn8AdMaLA0wyl6vTz/uJVZoZ7RY5vEx3T0VBhlBAIjDOwbmV1uHyDJ7Md/8ZEKpJhcLoNZckxaM7HoLqTN1tLgmWY8VunWGXOvdSAdfyAqhyHJvYx6gJ9Gssi52zjfNwZFS0z5l+LjtdmuX0fn9Rh0rDTMJo
  template:
    metadata:
      labels:
        app: forgejo
      name: forgejo-app-db-secret
      namespace: forgejo
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-cnpg-rustfs-secret
  namespace: forgejo
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCVORGauIfNc+Ro+QDL1lWoqVj+yUEBHn6A0YEAHaZ6gxqphpYu8NOe0pMmFCqdQFlERHCJgetEInK8OhzrCTJwm8f4w1CWmwJsC+3h4Q3m0PADfVKb0gMdnT/G8oHql1zuPgkloDwbwXvREEYPJfzwcSKxI5FAa7OaSwleyAlsLAQgtk4rFeRmMsWc1r+j4JYNQn7NT0e97ykbT9qb0TMaBW6/Fim30tf//8DK79E+amQ285kkHzNE3cs4WCqsWQGRs9i2sLmFQ86vFCUAWtRvBn7FpwOCg/FFDdcYfmUa0YrZ4w7RkIwCMikPdYQu2izGrcb2IVf2fqUcxZsyDKQizJds+7cNx3SzWbZ2DAF79jAUTVeOQZsq0R2gbOWpb/O+hATUcdoCxaAX1vAAbnEXuELdcVcaEXUBY7zKQ9tj693Q9nH7ok9WrvXtI+1V5LBmofVuc9ldQlXgnD0u//FxBiIMAO/et6sfzwhSSiaSxpT1/xO7UaDTt4FSE1dqZGRQYjMcfNh6GxIILED46OL6CTYUEa8MSX9ML+8LBrLGgaFX4FdSgeE3m2PbP6MQmdwqeOLan9O4hatwFQV0lzfUEepy+McegYSSV5RtqitqerZBSF9yUxBSPeunPtqS3aIUSETJoC0Qnkjha8VIEToteWtd30KM4goJBMX/ewrt3dJXpER2e4x4vtEtq67dur8BiYJbHkjZ6H9r+q8=
    ACCESS_SECRET_KEY: AgBaAQxXludKmyD3+BQXsNjvJtDUC407o+Bxf6eqxEjpYQh8LAlpX5ssUL8YBAvtdhqWM8AjBh9UH12sbnPHyx6YZUi2PAXoyBZQK79FRe5PMuGSOSBY81G6iRoj8hUurEt9DBgQ28R9vmHMoaXVvji5lvAEzyf73/JLXbI34P/tmkndMTSv7W7H07PVaqOGmp2OKLuGIH9Qwfv0UTiFcdA51EJ7C8ffm4mYe0Z2j02c//y3pCiWy26aGq0/5zjBQRKjwhtFDLXYOMV0/rIvfTViWVDCJBHydurvYjPIODfwuB535RoJfP9fhLQGkylOM9UOimCYuCatNHKvyxFzUyIfLouihnqp1ftrrQOg94gXhibX77QgKiCPg5dfqxlk6H7CzXzR/ZVNlYc3zV0DxS1/xLCsgG3G7hkpd52lcmIWcXjpZlqqchawcDYgrmp0awfugJX2jSKVt4tPHRnrHxsnBWFeMppnL7t7CkDq3LGEIkRedkBSSpNODgrjMOOb3/pESEJ3nplY5Ugy9Z4MVeY1hriQo1WSqVdc1QaoSAxCn5crlo0iH35V9QbYVlE8pJUpZ+OfV46UnzOPFSFzGYoxPTtY/dyQO6yrXXY21UtQ9PlwHexF4OSFY37p3ODLyhhfxcEKc5y02qXk5w3Ny5N1HiqnL5nRd/F8XxUxgLDhm2rDotgwWUKKN7e1fSGnzneT1ddDJa1n3fQzix5MIgs3Y47pGcCiHFYeS851LjfrUOIfGVeNvU6j
  template:
    metadata:
      labels:
        app: forgejo
      name: forgejo-cnpg-rustfs-secret
      namespace: forgejo
    type: Opaque
