---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBk8cQZL5eDIZGBE4MOaJaA5ya4m3SjX/5jjjh3U0TCNKFZN5D5QtXUp6FpHlijfe87S3OzMtXi6FCLDQqED27q7jItTpHoLGCgIryX49yH3H0KhmXoXw9XZzwsfjlCSWV6e4wJpA4F3p1NaL6iw/J98pW9U/ENwF1KkUYcDebs5Zw6V6mEK8ROS26QeMmZhFXnpDwezQAoZzIX+32nvUfqQKUoV+sPwxuvLlieOpBJ/SWoLfttpyjUAauj6uKS80/biajTAW4xxYojtDrYgLXt8leXZfmd/Hct0dRnNizfb7D69rVPibZuzRCWIEGUYWFa814bhRl8HGtR98YTlcLnuLWSTpJ7fRj9ghO+3JnpaKbyaScTif7w4RJF0mqV/PCY9k4Q28Gz7bNNVbilnFw3eiDwxQQ8GK1PW8TAVArz+Ct+X4ZPXV4C+jF9REnlFX0HAZ5I+tq9InZ38TD4qdyyYEfV4VOIwKfi1+z03xwBua7TpAp1b6PFqwHe+fekiIyqhkhBWroXciboLK3yHf4z2hC1zz+8UplfuHYwCSu+EcJj2rJURD0SwbveezPd85F0kqtRd5YJTVITjsOOMi7CsZjVk05BNZqdWw+6kfbh2NMTmfuZGSi7HvW87JHDgKD6zYZZwSy6Q9EBz+97pRuBl7bSQfbSKopVdfCCoa+UG/KUcOTEZLL90iAj4KF26SfS1qjba3/7NYDL+7filIboXg==
    client_secret: AgBxbvXjdvsoYDGFnUmRKHuSiwnaH0cj/cOPhvviChWXe1KPSPgcEAmfVx2Q1s/B5b3Qohw6PEWRHi6XGSYKAVaAN1CYis7KsJcKhAP6IpG9oFjqbwnmOLkFgnF5I+N8NZJRgYsia3huH01GJf+i7h6vFtZEchbAF375kGZ152somQ6SXnEB4HA/9kYXwOwOZD8/SL1+RWUE7jc/rh95yG7ZH1y7e6Fk4BtzN7ppEehqyr8aDHdYRonYLBOkt5dcf/9DdgCe6OAoTjuPmHJk4jDfiY+gedudPVZ7vyTdMxRPQFjgcgqZT3gzPSmfLUGpo5A/ZLS/csJxvA7Oj/RBiP1SsEl60oH0WqJrxIugm/wmo638XQC0z0hIrMkn6GOoG8+YxMO9gJDupMJumbnbJQBsG6p/M6zjwcGF9rdTjJyx3hjI2mODBg8bVf2nWLW757RJA1Du35ufgsC1Tn4SNdv1WwjfukYDd03TDTD53mmCf+ljtgIIEzmi9TFubN5gQEMsbHqCPzcgtP6B0SFbj+XWTWAHhNSSYgi7EyPJvfigXC3Oer49K2HUeKE6cWkBL+sWfH7l3JG5/mzYhCGqaUQjkSaYnMFGCY9T71lIoantBIXhKSlobfv8dmsgGLHUAGvXnI4vQFXmWlHClQtGdUgDPbLlhehl4M97rcHN/PVXinxFXc+uU4mGXjKS2sPxfoFNwG4gkUYt3ZEkGQcjy1aDmYgT1jJj01umwTuCX2puomGX5u+dj7Uy00Og2NTiVsnigJy3DLA4U4P4T92QNVM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: operator-oauth
      namespace: tailscale
    type: Opaque
