---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-ui-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgAj0ym0lHSn10kHVgNnAAAAlV5uBUb+MF1iqPW+E6umnUuMjfSNjWY7bHwYXYVV5fC+NuHYHLz4ixE7fK/wyqiqnVzBt5k2j1NwmWrcLO0GgFNsWQ4dOokJRhmomgI0d7J2OsVWKCvcB/YO3Fz/SyVWTnKnG23nPpc3a3+pZDHN5hFLDtjWo++7sSflLzxBihFKsyWzgIVQ7EUN5QKvJDbvAxXIsntT9Uk8nZcFpgZgOWqOKQfq6RRflhEBuN0Ibo62m8cNPtENGA2U3VDK7U6vOzCB3w2IcGjFvO/DQ7KBAG1cyY0tzjSHiwFUYZdhyOGYHFOQ40RHS5E8iQh1FftG5byifRiSv9ST21LZpJAj/NI4oCdQ4Upf3CJOQiO9NEnHrJ/GB7skkTIkzdkCQT2bSnqiHUodxb22AsSkh/EpXf7FISXvvKCeoLjnhJaLSum6GXrt+W3z8Mf1Mv3Wte69gjK/rgj6AZOYfmMdW3ew+wBzPPW87zMdptE8Ubi5hesWK9bCJPr2S9hycNRjnbgsQxlMXVykOR+Tc/1mxfBQaAUxe3c5VJvBCFOFNmiZqXL4BnqyMPh6qda6jyL7umTnvfIi4p5d1ziBeaVFORi9i1P80IKhyRLxoI38c0++LsMi6i2oQ2WaF+ICAPIv/NMrASmJkowb0/r97xecbbEIQl6+4CO/xVeROfnSN6e0kptRGOdyd2e2PFohQ96EfQ2UL1rh+uQO4ceSVfJ9ifyx0siRhj+76bainQZu67a6kYE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: longhorn-ui-auth
      namespace: longhorn-system
    type: Opaque
