image:
  tag: "2.1.5"

replicaCount: 1
strategy:
  type: Recreate

# -- Environment variables from secrets or configmaps to add to the stirling-pdf pods
envsFrom: []

deployment:
  extraVolumeMounts:
    - mountPath: /configs
      name: storage-volume

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  path: /configs
  volumeName: stirling-pdf

resources:
  limits:
    memory: 4096Mi
  requests:
    memory: 512Mi

service:
  servicename: stirling-pdf
