---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-iii-app-key
  namespace: firefly-iii
spec:
  encryptedData:
    APP_KEY: AgC7DzksHvW8QIMGdIA6MWjnqTMnqapLZIyvL1F8tMGmUIWwhSJ7i005Vu8aouULwUiv3aLcybHJKzDOn+hSD4ueCJd353FmnL0drLpxfUthQvoHt9Pv9Jkl93gtlZDM1YqTCXs0r6VWYMC9+xBm+b9gEsUUHWWOlVEsTgz5FTMcSM1+3jC0yTGE0KOn3XUQbvgJY899r2HjPTkgIe3F+U1jLifd/EH6EWp9ylRmB1wBk3l+Qj4TB7tv3kVXbWRia/wVson4gUZfHvyOTAwSw+MxSJju7coLBffRp7Hu7aQ08jSmPSqtBZIhqzZF3XihtpRL+ySjmKcQgc+jatIvRIzVUnW517P2a+w7Kvzw8eyIXpzn4AN9Khv8xy6hPFNBvdRJqlGntJHucFlOAN+s0mVuCcNVoYYHQWp1KoC9G43KR3acsTxAtRbhyPIy0bPwLkc5t3Ci0vKbyuTDiPclkDD5tDaHhYScqdT0jvgcpYS0LfErbQNkrEJ/PsA7Jn7MlYDpRTkrLJvaSUsT3/KSph4SfprPGaLZzSSuaJncueDcv/yWB4M5OUkY1CRUIFYhNfvoEEokXu5ur7InnNkEMsvzMEq88M4CIO3/n96ViCk4CZXaa3ez8BLvAzRwzA78EqnTbtXCfZVFd/q5R9R2kUoHN4FIL1/DNM2IfLmvOeA70gCXvOcB091aMS1K+BRmObBrOHeXT2FhXoCMwe1MSnP4tL0ub+XcZUkT6FrtljEFYw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app: firefly-iii
      name: firefly-iii-app-key
      namespace: firefly-iii
    type: Opaque
