---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-iii-app-db-secret
  namespace: firefly-iii
spec:
  encryptedData:
    password: AgB1+Z+AKUWwEVzpoLEiqCFfFlsnfB+pCSzDthRFKqSB9bIM/Kk9x5QP1pQPTvC38DFDqs4e5iZh//ga+snbtqWlIgO1KwUgWq+hFC9q3s44KbagCM7bm1GaWVTLOfxhMTOlyUzlw+k0dcGv1G5BSN5vm2ZSIimTbnOiFbY04C29tarBrHaVlZE7gizgXUAwL7SQqCSh2EEVc7QPgP+4VehRRzCb0ThxXJN0wcSR/INz5Ss2GTIPlSsb7WFY5DHLw4viFhkXboxJa+bxRXC0XDXlDwxzFwuSXX8JYMB5zqoniqbA4beLuMu6939c1ThFfP9WHSwwzbdHdW7H3EJnytgAayCS5zwVDpmKT4ef385JZMUpl8uccgmIjsQ07lT4K0sTpyWAijvLymnK9zpynWJDcgczDX7QzOhNWaVVZmOPaM1y6uw5mYIs1RQ1m5KVo/sLai7m6ELm9O0mBsp9k6XOD3UT7e/x1wGgYV5gC3ZWs8TZEcBxBklvUhOPlaVaNLfVoXgbFYMwfueA6h5crN6Bftudu6nktlhd6YSnJWT8imHnY+sfQuNoJ4cj3T/njcpjyP39uLHTP0WAUoIoljRAH2WWHdPhL7YxUPKrJT8VjFPjrnPENBgc5Li3ewl+nCXaBysEHuz2bzomGwWrGsUfOE5Yw15x+7fYh04ENesUbdE839J5RXPmlfmqbniDnhAaPyIXk4CcuYG5OlRd2q+s
    username: AgA4rZH00QOGOYYJUIhNkEgM9gL1NSovqwk46IYFcOeu0Vz7Jx2SpUzes+fRlEYtuk6uTkAm1sxhzBfChwkr95WYYfCmvD2m5k4xJAgXcdm8sOcwLCYaKEuuyTEX+OoQrT/vtwOdtPoshLdKoZ9HNFDnoq9H51R9MPl3vTVSf/jLcWmCKJNyb8k3pTq9dFO0tXpJvVc7q1l9TWi9wdg6LOUc6bLQZG3ISz8RZSTlZ5/6JWOT9CAyJ+uihzfBqBoQoithKYUI4bG/RDC2Y/vxhwiwrQvplPWixXfW1OELBpUxKxmf8BQgKVXI0ILrSx/lOIUs4QNWYOuEH2OVrzM5t2ncSRLQTtJl6Vg+X/paRxnml8/3Sw814V/ODvGeqkfcdsIB1Q7VP8H3/1ZMQSpoYMRs2kadEvqpc3nc8UDm5vPEFskK+0j2+f1Pjv5LqMDYeZ7A041KBS5+bhGssXZr4D6tazVq++SWzAq+Cif6tyrfZSsbr67jhOnIYMoG0IaPprkc6xKVj2mOm7p4oLYM3TrTnLFYfDQl1LefuCgHyiUSq1LhgUw0H9WjRD1K9UxORA1FmrI/v83XI3pAAVBzWU2xNva59JA7XMHaJHEIlGkqYC6Si1NHb6LrdFAa0ciSwnqYS/Fn/7dh8KANlagnei7qgkHBcAexUj84XOc+GBlZMbUCiLX5zwacalNAHGgVe0OPo5dAM1Ph
  template:
    metadata:
      labels:
        app: firefly-iii
      name: firefly-iii-app-db-secret
      namespace: firefly-iii
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-iii-cnpg-rustfs-secret
  namespace: firefly-iii
spec:
  encryptedData:
    ACCESS_KEY_ID: AgA5vVdaKJr2UnnmU7akWmIGUBU1brVvYFQWvnCO25thUSZbwAjiuTowH0NXVqZYXfneUsgH72rz7Ezf+K85jbAQXIonhACCCsbJpR179mqwFAkVL5xORcoF5ktsSor0mR6GR3EU+k2kQ4AdHwjfaWIv4dVaYfrGsMKv0OB8v8ipe8y72bMO5n3xIgqWpqrsUwKQWuWrid7Eghwx+BKxyDuTOriZfyXIIqcVnG54bAOKrEbHS92NCiN6C3jvDbcLT1FT4YvYZnyWADGHZs4mVtgXzTZvSjb2y8TfUcenO7YJpneSBUWVxe72YG8cVYCsNK5HfnQNkKfmo2jf3NY+sxQfWKuk8ObHkM5w5HReVS6de2FlGs5istfXdkxTQ2GUSlPK/4CBKn2kHKMUbqqA44f4fm8KWVNHlNSKUzsUwr4kpDiw7wKB3ha6/yWy2Ycao2MRg9aWPQijW4PU8OsdZwk1nCklZgU91ey70XP9MQRHg5Vbqp4TQd8Xm+Bvu3TZip3dROrJcdCJ34bOTjLHLUcKJ8Jki0y0wWfXEdck0E7zNoIjdLM6LsKAyL6DbxS2vcNWvm9+LBo51XeUyrOKoxvVV/teDr+skjsDJbKt/YoLVRAprqNWHispTZtdKI+42wPtpSjL6/3X/Qyz0zC9Z5AaYa5kTzaXwIg/3hZpKgEFtlBRn7VOOAzVr2qZ7semiZFK53d+IJ3M1pZH/ew=
    ACCESS_SECRET_KEY: AgANpQuc4KQ+PNmIb2hL7FMikpt0i/TRkzsUMNUFI9SYEjMQSh2vhuV+NK8UBNvA0CVphsgDgL3XJCFWBGD+edgQwL61aktL7ce9cw8UYlhFL+RdXPdT6xToetje1WMaL850g8ZMc54lWjH11jx7+zfterHXsohgZl7zYa4nl1wN7M1u2rIRJ6AXvTWP/o6JwmRnvL1qigflWa9nyGJvHMxCC3MOl1Pq2pK0Pw4RFIY79fqmMsa+NfrVbHTE+aJTfhdBStm0MLH3iiHUkJ4P0vABbcCAxilPsIdSVouPdDS+BrWLmoKsSIFVsaS5niObc+Ti95m3mbmyGHF33sF7XKIkRy5/5TJE0f/cU2lK2nc/uMaU9Z9kXWdn/ui9o7WI2w4PnXkyu0GK2njxf30FesgB4Y8ykObcGhyBllnVVH4u2ZuP/t2Px8hC9nAsAWiBdhxptR9jCywtN5Jze8mMmdrp6KD6eTc7nfR/OAGYFzs5Bx9Jhb1+0LIsZFooagSONq4xdohvhpHLATdOVhigM3TSgcafl2/FsyuL6gNNSZZKadKkIyA930m3dyB2+MHM/qQOVHychhpSzuOwr8+0PbRt0GIYwabZiLjAc4HyiJf4fAAx9gDel5S1BdU9Jm6n7N30yQs7eTuHSzSoucYrME0bdLmWyvP2jvctM6hCZo6r//PWQfWYyUOqgRFIhfC0ksM7UGvqHqvysr3pLkxB13UzJdccKEpcMsLnj/9IWdieg2ubLwSbN8Xg
  template:
    metadata:
      labels:
        app: firefly-iii
      name: firefly-iii-cnpg-rustfs-secret
      namespace: firefly-iii
    type: Opaque
