---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-iii-smtp
  namespace: firefly-iii
spec:
  encryptedData:
    MAIL_PASSWORD: AgC6lsob8tgoFLRLEZaCNCQKADYvKQBlej8TOsha/V/1Hk82nS7CUJP2ImymB5iDXiQUA8TOdqLT36N9IiWsJEeV7901poqrZlGGyM22og24mr3Wg2xkaA/UszNlCCbwoSbjoslnXfykAuuxPMjAPdHy+F5dzP1WRI61ZEYgHpMTMfllKffongGSg6GU1KfLuafkLlyI4NOmkdI4j2uiQ09GrYWPmdgUzWqY1ffP53Y7ZoXZhKryPKB/sCuuSt9hImTiBrucKXGkodE7DuSOUo65WtckHWM8lAbJySseiNP4tPLLTQL/qE5sLQe/F25FNMH5OHC+Ry2QECAcvcWfMhaFrPjcdIiiy/rEte7QUwfLVNV5icViQhxu2ThPibBqmw9NWLQ3ERcCCCweeuQnAInKXBov2CvJPEgCIKpssttnM/zJvdpfLB4W6ViUZjaLGAtJkT3CG//NJ/9GJ/gQKUmDxk6v8OFdSfLZmB9ZMKOJACgVfll3TTQ0MJa1Da7aSlb7FqI8wmsj0jQqyRPnOK9uqoPUGiEU52jh8+8oTIVzi2RAs1W0hA+6KtqgvTLoI7z4Aso18ZDc6DLE5BcEk2VFkUjdOdxZZwIESLRcYbVUcH3XcbsoJE45sSlsjzoAYt6uwQYtivGpXvpt5duQd+AzhDpH1z7h08fHLUcVzyofXJ/r2E6+P1Zyz7mXF+s4ieoyV0oLOoQuqIQ1rDIAjERyVnc4uAL9rJ2tqCtY9DNvo0kK3ETkZLrA9tMic6amr1xMZhrAfpwrXd0XelhcnFVxem/+R2xkz151TlUHYexvQeabllWEA3XnA5I=
    MAIL_USERNAME: AgA/P+SvETHmsaS4gF5iStClh9nbJJSIbFmwh2UasQIcsqKjDD7DilQ90TsebaSFccg+tSmQV5WSGUZ5x0x1AkkiIJyMwRo3nhp1ySYmOmKceaX5GQqAsCoo0YU2UGRbXfaVGyFBsj4LePna5lW/kIeVr/k1Fjo2eCKMVaLPg69GxfS8pS4Z88vQGU1eBQUu3Gk3R7qj8zLwmmNipKGRogKVsmH7ZWanjCxN0zfmm5T3CWQQ8PxHT/rzUOhm4EceBu44rjfGwKrTv+Z8RMRgNCkz+zGFeY6drgEDp0Vq+Fzu17PJCSWLE6hbPzGZ00TnLYCPvKc6eH+3NT/x1oqARbevtJn1qkdObu9zDwYW10nDmfWulkaLaS4PnQacH6kxuJbTH2vkg0+mZgj7tNaXVo58Cwq8aLB+IH5cNUeM25Gp/LafUUZaxNEUxgU/6m8hF0bV2aGEV0XOVnHZvg64IQPFveFnzxaXf3fVZH4uDwUqcbdu+FIt+Lyigre0Q2WOQzqqOfBKSygfMYaVjE3lSW+8AfSq0cGnv18qb/nnRXrA/lAXyfiXNGV4BIKFrUbKa0vzMiMAkgXCHc50UYH538Dt1eIUlgq1vsy7h0K9LE31ZZCe8L8zU/8bUAOlajh1pvN7ssHInk1q6341HwiFvGH3cQVB+fHuXKHpQ10B6fckh9K387Fyl0KS0Csm/cOpwMISm0rPFPNCdvewbGCB9bC5jAeRcd0=
  template:
    metadata:
      labels:
        app: firefly-iii
      name: firefly-iii-smtp
      namespace: firefly-iii
    type: Opaque
