apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools-ingressroute-certificate
  namespace: it-tools
spec:
  secretName: it-tools-certificate-secret-internal
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - it-tools.internal.dmhosted.com
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools-ingressroute-tailscale
  namespace: it-tools
spec:
  ingressClassName: traefik-tailscale
  entryPoints:
    - websecure
  routes:
    - match: Host(`it-tools.internal.dmhosted.com`)
      kind: Rule
      services:
        - name: it-tools
          port: 80
  tls:
    secretName: it-tools-certificate-secret-internal
