apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davmacario/dmhosted-infra
    targetRevision: main
    path: kubernetes/cloudflare-tunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
