apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-cloudflare
  namespace: argocd
  labels:
    name: external-dns
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.21.1
      helm:
        valueFiles:
          - $values/kubernetes/external-dns/cloudflare/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/external-dns/cloudflare
      directory:
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
