apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  labels:
    name: forgejo
spec:
  project: default
  sources:
    - repoURL: code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: 17.1.4
      helm:
        valueFiles:
          - $values/kubernetes/apps/forgejo/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/apps/forgejo
      directory:
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
