apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davmacario/dmhosted-infra
    targetRevision: main
    path: kubernetes/apps/it-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: it-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
