apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  labels:
    name: stirling-pdf
spec:
  project: default
  sources:
    - repoURL: https://stirling-tools.github.io/Stirling-PDF-chart # URL of the Helm chart
      chart: stirling-pdf/stirling-pdf-chart
      targetRevision: 3.1.0
      helm:
        valueFiles: # Using ref - see next item in list
          - $values/kubernetes/apps/stirling-pdf/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values

    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/apps/stirling-pdf
      directory: # Don't apply `values.yaml`, only other files
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
