apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    name: traefik
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 41.1.0
      helm:
        releaseName: traefik
        # TODO: 'adopt' CRDs
        skipCrds: true
        valueFiles:
          - $values/kubernetes/traefik/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/traefik
      directory:
        recurse: true
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
