apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-tailscale
  namespace: argocd
  labels:
    name: traefik-tailscale
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 41.3.0
      helm:
        # Traefik CRDs are owned by the primary traefik instance.
        skipCrds: true
        valueFiles:
          - $values/kubernetes/traefik-tailscale/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/traefik-tailscale
      directory:
        # Manifests live in the `dashboard/` subdirectory
        recurse: true
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-tailscale
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
