apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    name: uptime-kuma
spec:
  project: default
  sources:
    - repoURL: https://helm.irsigler.cloud
      chart: uptime-kuma
      targetRevision: 4.1.0
      helm:
        valueFiles:
          - $values/kubernetes/apps/uptime-kuma/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/apps/uptime-kuma
      directory:
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
