apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  labels:
    name: vaultwarden
spec:
  project: default
  sources:
    - repoURL: https://guerzon.github.io/vaultwarden
      chart: vaultwarden
      targetRevision: 0.43.1
      helm:
        valueFiles:
          - $values/kubernetes/apps/vaultwarden/values.yaml
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      ref: values
    - repoURL: https://github.com/davmacario/dmhosted-infra
      targetRevision: main
      path: kubernetes/apps/vaultwarden
      directory:
        exclude: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
