apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Static manifests
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.9.0/high-availability-1.21+.yaml
